In [787]:
import numpy as np

**1. Sales Data Analysis**

In [788]:
# OrderID	CustomerID	CustomerName	Segment	Region	OrderDate	ProductCategory	SalesAmount	Quantity	Discount	Profit salesRep
sales_data_np = np.array([
    [1001, 'C001', 'Alice Johnson', 'Consumer', 'East', '2025-08-01', 'Furniture', 1200.50, 2, 0.10, 300.12, 'William Clark'],
    [1002, 'C002', 'Bob Smith', 'Corporate', 'West', '2025-08-03', 'Office Supplies', 450.75, 5, 0.05, 90.15, 'Olivia Martinez'],
    [1003, 'C003', 'Carol Lee', 'Home Office', 'Central', '2025-08-05', 'Technology', 890.00, 1, 0.20, 150.50, 'James Wilson'],
    [1004, 'C004', 'David Kim', 'Consumer', 'South', '2025-08-07', 'Furniture', 670.80, 3, 0.15, 120.30, 'Olivia Martinez'],
    [1005, 'C005', 'Emma Davis', 'Corporate', 'East', '2025-08-09', 'Office Supplies', 310.25, 4, 0.00, 70.40, 'William Clark'],
    [1006, 'C006', 'Frank Wilson', 'Consumer', 'Central', '2025-08-11', 'Technology', 1500.00, 2, 0.25, 250.00, 'James Wilson'],
    [1007, 'C007', 'Grace Chen', 'Home Office', 'West', '2025-08-13', 'Furniture', 920.45, 1, 0.05, 200.10, 'Olivia Martinez'],
    [1008, 'C008', 'Henry Patel', 'Consumer', 'East', '2025-08-15', 'Office Supplies', 540.60, 6, 0.10, 130.50, 'William Clark'],
    [1009, 'C009', 'Irene Lopez', 'Corporate', 'South', '2025-08-17', 'Technology', 720.00, 3, 0.15, 180.00, 'William Clark'],
    [1010, 'C010', 'Jack Brown', 'Consumer', 'Central', '2025-08-19', 'Furniture', 1100.80, 4, 0.20, 250.00, 'Olivia Martinez']
])
sales_data_np

array([['1001', 'C001', 'Alice Johnson', 'Consumer', 'East',
        '2025-08-01', 'Furniture', '1200.5', '2', '0.1', '300.12',
        'William Clark'],
       ['1002', 'C002', 'Bob Smith', 'Corporate', 'West', '2025-08-03',
        'Office Supplies', '450.75', '5', '0.05', '90.15',
        'Olivia Martinez'],
       ['1003', 'C003', 'Carol Lee', 'Home Office', 'Central',
        '2025-08-05', 'Technology', '890.0', '1', '0.2', '150.5',
        'James Wilson'],
       ['1004', 'C004', 'David Kim', 'Consumer', 'South', '2025-08-07',
        'Furniture', '670.8', '3', '0.15', '120.3', 'Olivia Martinez'],
       ['1005', 'C005', 'Emma Davis', 'Corporate', 'East', '2025-08-09',
        'Office Supplies', '310.25', '4', '0.0', '70.4', 'William Clark'],
       ['1006', 'C006', 'Frank Wilson', 'Consumer', 'Central',
        '2025-08-11', 'Technology', '1500.0', '2', '0.25', '250.0',
        'James Wilson'],
       ['1007', 'C007', 'Grace Chen', 'Home Office', 'West',
        '2025-08-13', 'F

1 .Count total sales per product category.

In [789]:
category = np.unique(sales_data_np[:,-6])
for i in category:
  category = sales_data_np[:,6]==i
  Furniture_data = sales_data_np[category]
  quantity_furniture = Furniture_data[:,-4].astype(int)
  total_quantity_furniture = np.sum(quantity_furniture)
  print(f'total number of sales in "{i}"',total_quantity_furniture)

total number of sales in "Furniture" 10
total number of sales in "Office Supplies" 15
total number of sales in "Technology" 6


2. Calculate the total revenue generated by each sales representative.

In [790]:
representative = np.unique(sales_data_np[:,-1])
for i in representative:
  profit = sales_data_np[:,-1]==i
  profits = sales_data_np[profit][:,-2].astype(float)
  total_profit = np.sum(profits)
  print(f'profites by {i} :',total_profit)

profites by James Wilson : 400.5
profites by Olivia Martinez : 660.55
profites by William Clark : 681.02


3. Find the product with the highest sales.


In [791]:
index = sales_data_np[:,-4].astype(float) ==sales_data_np[:,-4].astype(float).max()
print(f'product details with highest sales {sales_data_np[index]}')

product details with highest sales [['1008' 'C008' 'Henry Patel' 'Consumer' 'East' '2025-08-15'
  'Office Supplies' '540.6' '6' '0.1' '130.5' 'William Clark']]


4. Group data by sales regions and calculate average sales.

In [792]:
sales_regions = np.unique(sales_data_np[:,4])

for i in sales_regions:
  index = sales_data_np[:,4]==i
  temp = sales_data_np[index]
  print(f'average sales in {i} : {np.mean(temp[:,-5].astype(float))}')

average sales in Central : 1163.6000000000001
average sales in East : 683.7833333333333
average sales in South : 695.4
average sales in West : 685.6


----------------------------------

**2. Employee Data Analysis**

In [793]:
import numpy as np
# EmployeeID	Name	Department	Salary	PerformanceScore
employee_data = np.array([
    ['E001', 'Alice Brown', 'HR', 55000, 8.5],
    ['E002', 'Bob Smith', 'IT', 72000, 7.2],
    ['E003', 'Carol Lee', 'Finance', 68000, 9.0],
    ['E004', 'David Kim', 'IT', 75000, 6.5],
    ['E005', 'Emma Davis', 'Marketing', 50000, 8.0],
    ['E006', 'Frank Wilson', 'HR', 53000, 7.8],
    ['E007', 'Grace Chen', 'Finance', 67000, 8.9],
    ['E008', 'Henry Patel', 'Marketing', 52000, 7.5],
    ['E009', 'Irene Lopez', 'IT', 71000, 9.3],
    ['E010', 'Jack Brown', 'HR', 56000, 6.8]
])

Count the number of employees per department

In [794]:
department = np.unique(employee_data[:,-3])
for i in department:
  print(f'number of employees in {i} : {len(employee_data[employee_data[:,-3]==i])}')

number of employees in Finance : 2
number of employees in HR : 3
number of employees in IT : 3
number of employees in Marketing : 2


Find the employee with the highest salary.

In [795]:
max_Salary = employee_data[:,-2]
emp = employee_data[employee_data[:,-2] == max(max_Salary)]
print(f'employee with the highest salary.{emp}')

employee with the highest salary.[['E004' 'David Kim' 'IT' '75000' '6.5']]


Calculate average salary per department.

In [796]:
department = np.unique(employee_data[:,2])
# print(department)
for i in department:
  index = employee_data[:,2]==i
  temp = employee_data[index]
  print(f'average sales in {i} : {np.mean(temp[:,3].astype(float))}')
  print()

average sales in Finance : 67500.0

average sales in HR : 54666.666666666664

average sales in IT : 72666.66666666667

average sales in Marketing : 51000.0



Sort employees based on their performance score or salary.


In [797]:
sorted_indices = np.argsort(employee_data[:, -1])
sorted_employee_data = employee_data[sorted_indices]
print('sorted data')
sorted_employee_data

sorted data


array([['E004', 'David Kim', 'IT', '75000', '6.5'],
       ['E010', 'Jack Brown', 'HR', '56000', '6.8'],
       ['E002', 'Bob Smith', 'IT', '72000', '7.2'],
       ['E008', 'Henry Patel', 'Marketing', '52000', '7.5'],
       ['E006', 'Frank Wilson', 'HR', '53000', '7.8'],
       ['E005', 'Emma Davis', 'Marketing', '50000', '8.0'],
       ['E001', 'Alice Brown', 'HR', '55000', '8.5'],
       ['E007', 'Grace Chen', 'Finance', '67000', '8.9'],
       ['E003', 'Carol Lee', 'Finance', '68000', '9.0'],
       ['E009', 'Irene Lopez', 'IT', '71000', '9.3']], dtype='<U32')

---------------------------
**3. Student Grades Analysis**
---------------------------

In [798]:
import numpy as np
#StudentID	Name	Math	Science	English	History
student_data = np.array([
    ['S001', 'Alice Brown', 85, 78, 92, 74],
    ['S002', 'Bob Smith', 58, 64, 10, 66],
    ['S003', 'Carol Lee', 95, 18, 82, 91],
    ['S004', 'David Kim', 76, 85, 20, 79],
    ['S005', 'Emma Davis', 66, 72, 68, 70],
    ['S006', 'Frank Wilson', 90, 95, 88, 92],
    ['S007', 'Grace Chen', 72, 10, 75, 65],
    ['S008', 'Henry Patel', 81, 79, 85, 80],
    ['S009', 'Irene Lopez', 69, 14, 17, 71],
    ['S010', 'Jack Brown', 88, 10, 86, 19]
])


1.Count the number of students who passed each subject.

In [ ]:
count=0
for i in student_data:
  marks = i[2:].astype(int)
  # print(marks)
  total = sum(marks>20)
  # print(total)
  if total == 4:
    count+=1
print(f'the number of students who passed each subject : {count}')

the number of students who passed each subject : 4


2.Calculate the average marks per subject.


In [ ]:
sub=['Math'	,'Science',	'English'	,"History"]
avg = np.mean(student_data[:,2:].astype(int),axis=0)
j=0
for i in sub:
    print(i," ",avg[j])
    j+=1

avg of Math : 780
avg of Science : 525
avg of English : 623
avg of History : 707


3.Find the student with the highest total marks

In [ ]:

print(student_data[np.argmax(np.sum(student_data[:,2:].astype(int),axis=1))])###



max_marks = 0
name = ''
for i in student_data:
  marks = i[2:].astype(int)
  total = sum(marks)
  if max_marks<total:
    max_marks = total
    name = i[1]
print(f'{name} : {max_marks}')


Frank Wilson : 365


4.Determine the top 3 students based on average marks.

In [ ]:
student_data[np.argsort(np.mean(student_data[:,2:].astype(int),axis=1))][::-1][0:3]#####


marks = student_data[:,2:].astype(int)
mean_marks = np.mean(marks,axis=1)
sorted = np.sort(mean_marks)[::-1]
for i in range(1,4):
  for j in student_data:
    marks = j[2:].astype(int)
    if np.mean(marks)==sorted[i]:
      print(f'student {i} : {j[1]} , (Avg Marks) = {sorted[i]}')

student 1 : Alice Brown , (Avg Marks) = 82.25
student 2 : Henry Patel , (Avg Marks) = 81.25
student 3 : Carol Lee , (Avg Marks) = 71.5


______________________________

**4. Weather Data Analysis**

In [803]:
import numpy as np

# WeatherID   Month    Temp(°C)  Rainfall(mm)
weather_data = np.array([
    ['W001', 'January',   22,  10],
    ['W002', 'January',   24,   5],
    ['W003', 'January',   20,   8],

    ['W004', 'February',  25,   7],
    ['W005', 'February',  27,  12],
    ['W006', 'February',  23,   9],

    ['W007', 'March',     30,   4],
    ['W008', 'March',     32,   6],
    ['W009', 'March',     28,   5],

    ['W010', 'April',     34,   2],
    ['W011', 'April',     36,   3],
    ['W012', 'April',     35,   1],

    ['W013', 'May',       37,   0],
    ['W014', 'May',       38,   2],
    ['W015', 'May',       39,   1],

    ['W016', 'June',      40,  30],
    ['W017', 'June',      39,  25],
    ['W018', 'June',      41,  28],

    ['W019', 'July',      36,  45],
    ['W020', 'July',      37,  42],
    ['W021', 'July',      35,  50],

    ['W022', 'August',    33,  40],
    ['W023', 'August',    34,  38],
    ['W024', 'August',    35,  35],

    ['W025', 'September', 32,  25],
    ['W026', 'September', 31,  28],
    ['W027', 'September', 33,  22],

    ['W028', 'October',   28,  15],
    ['W029', 'October',   27,  18],
    ['W030', 'October',   29,  12],

    ['W031', 'November',  24,  20],
    ['W032', 'November',  26,  22],
    ['W033', 'November',  23,  18],

    ['W034', 'December',  21,  30],
    ['W035', 'December',  22,  25],
    ['W036', 'December',  20,  28]
])

1.Find the maximum and minimum temperature recorded each month.

In [ ]:
month = np.unique(weather_data[:,1])###
for i in month:
    monthdata = weather_data[weather_data[:,1]==i]
    max = monthdata[np.argmax(monthdata[:,2].astype(float))][2]
    min = monthdata[np.argmin(monthdata[:,2].astype(float))][2]
    print(i," ",min," ",max)


months = np.unique(weather_data[:,1])
for i in months:
  index = weather_data[:,1]==i
  filtered = weather_data[index]
  print(f'max temp in the month {i} : {np.max(filtered[:,2].astype(int))} deg')
  print(f'min temp in the month {i} : {np.min(filtered[:,2].astype(int))} deg')
  print()

max temp in the month April : 36 deg
min temp in the month April : 34 deg

max temp in the month August : 35 deg
min temp in the month August : 33 deg

max temp in the month December : 22 deg
min temp in the month December : 20 deg

max temp in the month February : 27 deg
min temp in the month February : 23 deg

max temp in the month January : 24 deg
min temp in the month January : 20 deg

max temp in the month July : 37 deg
min temp in the month July : 35 deg

max temp in the month June : 41 deg
min temp in the month June : 39 deg

max temp in the month March : 32 deg
min temp in the month March : 28 deg

max temp in the month May : 39 deg
min temp in the month May : 37 deg

max temp in the month November : 26 deg
min temp in the month November : 23 deg

max temp in the month October : 29 deg
min temp in the month October : 27 deg

max temp in the month September : 33 deg
min temp in the month September : 31 deg



2.Calculate average rainfall per season.

In [ ]:
# season = ['Spring','Summer',"Autumn",'Winter']
season = ['winter','Monsoon',"autunmn",'summer']

sea = np.unique(weather_data[:,0])###########
for i in sea:
    seadata = weather_data[weather_data[:,0]==i]
    mean_rain = np.mean(seadata[:,-1].astype(float))
    print(i," ",mean_rain)

months = np.unique(weather_data[:,1])
count = 0
for i in season:
  raing_data = weather_data[count:(count+3),-1].astype(int)
  print(f'avg rainfall in {i} :',np.mean(raing_data))
  count+=3


avg rainfall in winter : 7.666666666666667
avg rainfall in Monsoon : 9.333333333333334
avg rainfall in autunmn : 5.0
avg rainfall in summer : 2.0


3.Count how many days had temperature above a threshold (e.g., >35°C)

In [806]:
temp = weather_data[:,-2].astype(int)>35
print('days had temperature above a threshold (e.g., >35°C) :',sum(temp))

days had temperature above a threshold (e.g., >35°C) : 9


4.Identify the month with the highest average temperature.

In [ ]:
month = np.unique(weather_data[:,1])#####
temp = []
for i in month:
    monthdata = weather_data[weather_data[:,1]==i]
    monttemp = np.mean(monthdata[:,-2].astype(float))
    temp.append(monttemp)
print(month[np.argmax(temp)]," ",temp[np.argmax(temp)])


months = np.unique(weather_data[:,1])
count = 0
max_avg_temp=0
monthName=''
for i in months:
  monthdata = weather_data[weather_data[:,1]==i]
  if max_avg_temp < np.mean(monthdata[:,-2].astype(int)):
    max_avg_temp = np.mean(monthdata[:,-2].astype(int))
    monthName = i
print(f'highest average temperature "{i}" , avg_temp : {max_avg_temp} C')


highest average temperature "September" , avg_temp : 40.0 C


________________________________
**5. Stock Market Data Analysis**

In [808]:
import numpy as np

# StockID   Date        Company        Price
stock_data = np.array([
    ['ST001', '2025-01-01', 'AlphaTech',   150],
    ['ST002', '2025-01-01', 'BetaCorp',    220],
    ['ST003', '2025-01-01', 'GammaLtd',    310],

    ['ST004', '2025-01-02', 'AlphaTech',   155],
    ['ST005', '2025-01-02', 'BetaCorp',    215],
    ['ST006', '2025-01-02', 'GammaLtd',    320],

    ['ST007', '2025-01-03', 'AlphaTech',   160],
    ['ST008', '2025-01-03', 'BetaCorp',    225],
    ['ST009', '2025-01-03', 'GammaLtd',    315],

    ['ST010', '2025-01-04', 'AlphaTech',   158],
    ['ST011', '2025-01-04', 'BetaCorp',    230],
    ['ST012', '2025-01-04', 'GammaLtd',    318],

    ['ST013', '2025-01-05', 'AlphaTech',   162],
    ['ST014', '2025-01-05', 'BetaCorp',    228],
    ['ST015', '2025-01-05', 'GammaLtd',    325],

    ['ST016', '2025-01-06', 'AlphaTech',   165],
    ['ST017', '2025-01-06', 'BetaCorp',    235],
    ['ST018', '2025-01-06', 'GammaLtd',    330]
])


1 Calculate daily returns for each stock

In [809]:
stock = np.unique(stock_data[:,2])
for i in stock:
  temp = stock_data[stock_data[:,2]==i]
  print('stock ',i)
  for j in range(0,len(temp)-1):
    returns = (temp[j+1,-1].astype(int)-temp[j,-1].astype(int))/temp[j,-1].astype(int)
    print(f'day{j+1} returns',returns.round(2))
  print()



stock  AlphaTech
day1 returns 0.03
day2 returns 0.03
day3 returns -0.01
day4 returns 0.03
day5 returns 0.02

stock  BetaCorp
day1 returns -0.02
day2 returns 0.05
day3 returns 0.02
day4 returns -0.01
day5 returns 0.03

stock  GammaLtd
day1 returns 0.03
day2 returns -0.02
day3 returns 0.01
day4 returns 0.02
day5 returns 0.02



2 Find the stock with the highest average return.

In [810]:

for stock in stock:
    temp = stock_data[stock_data[:, 2] == stock]
    temp = temp[temp[:, 1].argsort()]

    prices = temp[:, -1].astype(float)
    returns = (prices[1:] - prices[:-1]) / prices[:-1]

    avg_return = np.mean(returns)
    print(f'Average daily return of {stock}: {avg_return:.4f} ({avg_return*100:.2f}%)')


Average daily return of AlphaTech: 0.0194 (1.94%)
Average daily return of BetaCorp: 0.0136 (1.36%)
Average daily return of GammaLtd: 0.0127 (1.27%)


3 Count how many days each stock had a positive return.

In [811]:
stock = np.unique(stock_data[:,2])
for i in stock:
  temp = stock_data[stock_data[:,2]==i]
  count=0
  for j in range(0,len(temp)-1):
    returns = (temp[j+1,-1].astype(int)-temp[j,-1].astype(int))/temp[j,-1].astype(int)
    if returns>0:
      count+=1
  print(f'{i} has positive return for {count} days',)
  print()

AlphaTech has positive return for 4 days

BetaCorp has positive return for 3 days

GammaLtd has positive return for 4 days



4 Determine the maximum drawdown (largest fall from peak price).

In [812]:
stock = np.unique(stock_data[:,2])
for i in stock:
  temp = stock_data[stock_data[:,2]==i]
  temp_ret = (temp[0+1,-1].astype(int)-temp[0,-1].astype(int))/temp[0,-1].astype(int)
  for j in range(1,len(temp)-1):
    returns = (temp[j+1,-1].astype(int)-temp[j,-1].astype(int))/temp[j,-1].astype(int)
    if returns<temp_ret:
      temp_ret=returns
  print(f'max downfall of {i} is ',temp_ret.round(3))


max downfall of AlphaTech is  -0.012
max downfall of BetaCorp is  -0.023
max downfall of GammaLtd is  -0.016


**6. Hospital Patient Data Analysis**

In [813]:
import numpy as np

#patient_id age department disease_category days_stayed
data = np.array([
    ('P001', 45, 'Cardiology', 'Heart Disease', 7),
    ('P002', 30, 'Neurology', 'Stroke', 10),
    ('P003', 65, 'Orthopedics', 'Fracture', 5),
    ('P004', 50, 'Cardiology', 'Heart Disease', 12),
    ('P005', 40, 'Neurology', 'Migraine', 3),
    ('P006', 70, 'Cardiology', 'Arrhythmia', 8),
    ('P007', 60, 'Orthopedics', 'Arthritis', 15),
    ('P008', 55, 'Neurology', 'Stroke', 6),
    ('P009', 35, 'Cardiology', 'Heart Disease', 9),
    ('P010', 28, 'Orthopedics', 'Fracture', 4)
])
data.shape

(10, 5)

1 Count the number of patients per disease category.

In [814]:
category = np.unique(data[:,-2])
for i in category :
  patients = data[data[:,-2]==i]
  # print(patients)
  print(f'No of patients in {i} :{len(patients)}')
  print()

No of patients in Arrhythmia :1

No of patients in Arthritis :1

No of patients in Fracture :2

No of patients in Heart Disease :3

No of patients in Migraine :1

No of patients in Stroke :2



2 Find the patient with the longest hospital stay.

In [815]:
sortedData = np.argsort(data[:,-1].astype(int))
sorted_patients = data[sortedData]
print(f'patient with the longest hospital stay : {sorted_patients[-1]}')

patient with the longest hospital stay : ['P007' '60' 'Orthopedics' 'Arthritis' '15']


3 Calculate average age of patients per department.

In [816]:
department = np.unique(data[:,2])
for i in department:
  info = data[data[:,2]==i]
  avg = np.mean(info[:,1].astype(int))
  print(f'average age of patients in department {i} : ',avg)


average age of patients in department Cardiology :  50.0
average age of patients in department Neurology :  41.666666666666664
average age of patients in department Orthopedics :  51.0


4 Identify the most common diagnosis.

In [817]:
category = np.unique(data[:,-2])
name = ""
temp = 0
for i in category :
  patients = data[data[:,-2]==i]
  if len(patients)>temp:
    name=i
    temp=len(patients)
print(f' most common diagnosis "{name}"')

 most common diagnosis "Heart Disease"


**7 E-commerce Website Traffic Analysis**

In [818]:
import numpy as np

# 'visitor_id','date','pages_visited','time_spent',

data = np.array([
    ['V001', '2025-09-01', 5, 12.5],
    ['V002', '2025-09-01', 1, 3.0],
    ['V003', '2025-09-02', 3, 7.2],
    ['V001', '2025-09-02', 2, 6.5],
    ['V002', '2025-09-03', 1, 2.0],
    ['V003', '2025-09-03', 4, 15.0],
    ['V004', '2025-09-04', 3, 20.0],
    ['V002', '2025-09-05', 1, 1.5],
    ['V003', '2025-09-06', 2, 5.0],
    ['V001', '2025-09-07', 3, 10.]
])


1.Count the number of visitors per day/week.

In [819]:
uniqure_dates = np.unique(data[:,1])
for i in uniqure_dates:
  date = data[data[:,1]==i]
  visitors = np.sum(date[:,2].astype(int))
  print(f' visitors on date {i} :',visitors)

 visitors on date 2025-09-01 : 6
 visitors on date 2025-09-02 : 5
 visitors on date 2025-09-03 : 5
 visitors on date 2025-09-04 : 3
 visitors on date 2025-09-05 : 1
 visitors on date 2025-09-06 : 2
 visitors on date 2025-09-07 : 3


2.Find the day with the highest number of visitors.

In [820]:
temp = 0
day = ''
uniqure_dates = np.unique(data[:,1])
for i in uniqure_dates:
  date = data[data[:,1]==i]
  visitors = np.sum(date[:,2].astype(int))
  if visitors>temp:
    temp=visitors
    day=i
print('day with the highest number of visitors :',day,f'({temp})')

day with the highest number of visitors : 2025-09-01 (6)


3 Calculate average time spent by users on the website.

In [821]:
uniqure_users = np.unique(data[:,0])
for i in uniqure_users:
  user = data[data[:,0]==i]
  avg_time = np.mean(user[:,-2].astype(int))
  print(f'avg time spent by user ({i}) : {avg_time}')

avg time spent by user (V001) : 3.3333333333333335
avg time spent by user (V002) : 1.0
avg time spent by user (V003) : 3.0
avg time spent by user (V004) : 3.0


4 Determine bounce rate (users who visited only 1 page).



In [822]:
page_Visits = data[:,2].astype(int)
One_page_Visits = np.sum(page_Visits==1)
bounceRate = (One_page_Visits/len(page_Visits))*100
print('bounce rate',bounceRate,'%')

bounce rate 30.0 %


**Transportation Data Analysis**

In [823]:
import numpy as np

# Columns: [RouteID, VehicleID, Timestamp, PassengersOnBoard, Capacity]
data = np.array([
    ['R001', 'B001', '2025-09-01 07:15', 30, 50],
    ['R001', 'B002', '2025-09-01 19:30', 45, 50],
    ['R002', 'B003', '2025-09-01 07:45', 20, 40],
    ['R002', 'B004', '2025-09-01 19:00', 35, 40],
    ['R003', 'B005', '2025-09-01 08:00', 50, 60],
    ['R003', 'B006', '2025-09-01 19:30', 55, 60],
    ['R001', 'B007', '2025-09-01 19:00', 40, 50],
    ['R002', 'B008', '2025-09-01 18:30', 38, 40],
    ['R003', 'B009', '2025-09-01 19:00', 60, 60],
    ['R001', 'B010', '2025-09-01 19:30', 35, 50]
], dtype=object)


1 Count the number of passengers per route.

In [824]:
routes = np.unique(data[:,0])
for i in routes:
  transportData = data[data[:,0]==i]
  passengers = np.sum(transportData[:,-2].astype(int))
  print(f'total number of passengers in route {i} : ',passengers)

total number of passengers in route R001 :  150
total number of passengers in route R002 :  93
total number of passengers in route R003 :  165


2 Calculate average occupancy per bus/train.

In [825]:
routes = np.unique(data[:,0])
for i in routes:
  transportData = data[data[:,0]==i]
  passengers = np.sum(transportData[:,-2].astype(int))
  capacity = np.sum(transportData[:,-1].astype(float))
  print(f'avg occupancey per bus in rout {i} :',(np.round(passengers/capacity,2)))


avg occupancey per bus in rout R001 : 0.75
avg occupancey per bus in rout R002 : 0.78
avg occupancey per bus in rout R003 : 0.92


3 Find the route with maximum passengers.

In [826]:
rount_name=''
total_passengers = 0
routes = np.unique(data[:,0])
for i in routes:
  transportData = data[data[:,0]==i]
  passengers = np.sum(transportData[:,-2].astype(int))
  if total_passengers<passengers:
    total_passengers = passengers
    rount_name = i
print(f'route {rount_name} maximum passengers : ',total_passengers)

route R003 maximum passengers :  165


Identify peak hours of usage.


In [827]:
time = data[:,2]
time = [int(i[10:13]) for i in time]
value=0
count=0
for i in time :
  if time.count(i)>count:
    value = i
    count=time.count(i)
print(f'peak hours of usage : {value}:00')

peak hours of usage : 19:00


**9. Retail Store Inventory Analysis**

In [828]:
import numpy as np

# Columns: [ProductID, Category, ProductName, StockLevel, ReorderThreshold]
inventory_data = np.array([
    ['P001', 'Beverages', 'Cola 500ml', 120, 50],
    ['P002', 'Beverages', 'Orange Juice 1L', 45, 60],
    ['P003', 'Snacks', 'Potato Chips 200g', 80, 40],
    ['P004', 'Snacks', 'Chocolate Bar 50g', 25, 30],
    ['P005', 'Dairy', 'Milk 1L', 60, 40],
    ['P006', 'Dairy', 'Cheddar Cheese 200g', 15, 20],
    ['P007', 'Bakery', 'Whole Wheat Bread', 35, 25],
    ['P008', 'Bakery', 'Croissant Pack (4)', 10, 15],
    ['P009', 'Household', 'Laundry Detergent 2kg', 90, 30],
    ['P010', 'Household', 'Dish Soap 500ml', 50, 20]
], dtype=object)


1.Count the total number of products in stock.


In [829]:
stock = inventory_data[:,-1]
print(f'total number of products in stock',sum(stock>0))

total number of products in stock 10


2.Find the product with the lowest inventory.


In [830]:
sorted_data = inventory_data[np.argsort(inventory_data[:,-2])]
print(f'product wiht lowest inventory {sorted_data[0][1]}')

product wiht lowest inventory Bakery


3.Calculate average stock per product category.


In [831]:
category = np.unique(inventory_data[:,1])
for i in category:
  temp = inventory_data[inventory_data[:,1]==i]
  avg = np.mean(temp[:,-2])
  print(f'average stock in {i} : {avg}')

average stock in Bakery : 22.5
average stock in Beverages : 82.5
average stock in Dairy : 37.5
average stock in Household : 70.0
average stock in Snacks : 52.5


4 Identify products that need restocking (below threshold).

In [832]:
product = sorted_data[:3,:][:,2]
print('product that need restocking :')
for i in product:
  print(i)

product that need restocking :
Croissant Pack (4)
Cheddar Cheese 200g
Chocolate Bar 50g


**10 Sports Team Performance Analysis**

1 Count the number of wins per team

In [833]:
import numpy as np

# Columns: [MatchID, Team, Player, PointsScored, Result]
sports_data = np.array([
    ['M001', 'Tigers', 'Alice', 20, 'Win'],
    ['M001', 'Lions', 'Bob', 15, 'Loss'],
    ['M002', 'Tigers', 'Charlie', 18, 'Loss'],
    ['M002', 'Lions', 'David', 25, 'Win'],
    ['M003', 'Eagles', 'Eve', 30, 'Win'],
    ['M003', 'Tigers', 'Alice', 22, 'Loss'],
    ['M004', 'Eagles', 'Frank', 28, 'Loss'],
    ['M004', 'Lions', 'Bob', 32, 'Win'],
    ['M005', 'Tigers', 'Charlie', 24, 'Win'],
    ['M005', 'Eagles', 'Eve', 20, 'Loss'],
    ['M006', 'Lions', 'David', 18, 'Loss'],
    ['M006', 'Eagles', 'Frank', 26, 'Win'],
    ['M007', 'Tigers', 'Alice', 30, 'Win'],
    ['M007', 'Lions', 'Bob', 12, 'Loss'],
    ['M008', 'Eagles', 'Eve', 27, 'Win'],
    ['M008', 'Tigers', 'Charlie', 21, 'Loss']
], dtype=object)


1 Count the number of wins per team.

In [834]:
teams = np.unique(sports_data[:,1])
for i in teams:
  wins = sports_data[(sports_data[:,1]==i) & (sports_data[:,-1]=='Win')]
  print(f'{i} wins ',len(wins))

Eagles wins  3
Lions wins  2
Tigers wins  3


2 Find the player with the highest average score

In [835]:
player = np.unique(sports_data[:,2])
temp = 0
player_name = ""
for i in player:
  player_data = sports_data[sports_data[:,2]==i]
  avg = np.mean(player_data[:,-2])
  if avg>temp:
    temp = avg
    player_name = i
print(f'player whith highest avg score : {player_name} ({temp})')

player whith highest avg score : Frank (27.0)


3 Calculate total goals/runs/points scored by each team.

In [836]:
teams = np.unique(sports_data[:,1])
for i in teams:
  team_data = sports_data[(sports_data[:,1]==i)]
  total = sum(team_data[:,-2])
  print(f'total points scored by {i} : {total}')

total points scored by Eagles : 131
total points scored by Lions : 102
total points scored by Tigers : 135


4 Determine the most consistent performer based on statistics

In [837]:
teams = np.unique(sports_data[:,1])
name =""
temp =0
for i in teams:
  team_data = sports_data[(sports_data[:,1]==i)]
  avg = np.mean(team_data[:,-2])
  if avg>temp:
    temp = avg
    name = i

print(f'most consistent team "{name}" avg points {temp}')

most consistent team "Eagles" avg points 26.2


---
**NumPy 3D Array Transpose – Easy Problems**

Problem 1: Full Axis Permutation
Create a 3D array of shape (2, 3, 4).

In [1]:
import numpy as np
data = np.array([
    [[1,2,3,4],[5,6,7,8],[9,10,11,12]],
    [[13,14,15,16],[17,18,19,20],[21,22,23,24]],
])
print(data)
print(data.shape)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
(2, 3, 4)


Transpose it so that the shape becomes (4, 2, 3).

In [14]:
temp = data.transpose(2,1,0)
print(temp)
temp.shape

[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]


(4, 3, 2)

In [840]:
print('original')
print(data)
print('-------')
print('transposed')
print(temp)

original
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
-------
transposed
[[[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]

 [[ 4  8 12]
  [16 20 24]]]


In [841]:
print(temp[0,1,2])
print(temp[2,0,1])

21
7


---
**Problem 2: From (Batch, Channels, Height, Width) → (Batch, Height,
Width, Channels)**

In deep learning, images are often stored as (2, 3, 28, 28) → 2 images, 3 channels, 28×28 pixels.


In [842]:
data = np.random.rand(2,3,28,28)
data.shape

(2, 3, 28, 28)

• Transpose it to shape (2, 28, 28, 3).

In [843]:
temp = data.transpose(0,2,3,1)
temp.shape

(2, 28, 28, 3)

Confirm that element [1, 0, 10, 15] in original moves to [1, 10, 15, 0] in transposed.

In [844]:
print(data[1,0,10,15])
print(temp[1,10,15,0])
print(np.equal(data[1,0,10,15],temp[1,10,15,0]))

0.5521125462103117
0.5521125462103117
True


---
**Problem 3: Transpose Twice**

Create a 3D array of shape (3, 4, 5).

In [845]:
data = np.array([
    [[1,2,3,4,10],[5,6,7,8,10],[9,10,11,12,10],[9,10,11,12,10]],
    [[13,14,15,16,10],[17,18,19,20,10],[21,22,23,24,10],[9,10,11,12,10]],
    [[25,26,27,28,10],[29,30,31,32,10],[33,34,35,36,10],[9,10,11,12,10]],
])
data.shape

(3, 4, 5)

• First, transpose it to (5, 3, 4).

In [846]:
temp = data.transpose(2,0,1)
temp.shape

(5, 3, 4)

Then transpose the result back to (3, 4, 5) using another transpose.

In [847]:
ans = temp.transpose(1,2,0)
ans.shape

(3, 4, 5)

In [848]:
print(f'original and transpsed array are equal -> {np.array_equal(ans,data)}')

original and transpsed array are equal -> True


---
Problem 4: Multi-Step Swap

In [849]:
weather_data = np.random.rand(2, 12, 30)
weather_data

array([[[0.0725329 , 0.46807104, 0.87883842, 0.74636984, 0.57548315,
         0.75478752, 0.21621925, 0.2247566 , 0.33426713, 0.82279658,
         0.28569501, 0.16603983, 0.30991492, 0.68987165, 0.12885356,
         0.10343799, 0.78723531, 0.2915485 , 0.14240768, 0.4150559 ,
         0.87590454, 0.7666867 , 0.37140812, 0.65447526, 0.48040064,
         0.65611865, 0.85608147, 0.72896308, 0.03824624, 0.55393888],
        [0.45272139, 0.22090651, 0.26524971, 0.73108185, 0.00728268,
         0.72035542, 0.15084847, 0.86247628, 0.01473651, 0.44082961,
         0.88647107, 0.68113119, 0.41482967, 0.20278732, 0.20997013,
         0.35071052, 0.4313052 , 0.03575274, 0.65628176, 0.45527916,
         0.61392676, 0.52232074, 0.85385776, 0.68025816, 0.66584404,
         0.41993533, 0.05529353, 0.8329849 , 0.05357048, 0.01567409],
        [0.51324439, 0.82890592, 0.9827095 , 0.65020104, 0.17519872,
         0.53942556, 0.04720827, 0.46953659, 0.5520069 , 0.76952849,
         0.75415854, 0.95841222,

• Transpose it so that the shape becomes (30, 12, 2) → days first, years last.

In [850]:
temp = weather_data.transpose(2,1,0)
print(temp.shape)

(30, 12, 2)


Find the value at [year=1, month=5, day=10] in the original and confirm its new position in the
transposed array.

In [851]:
print(weather_data[1,5,10])
print(temp[10,5,1])
print(np.equal(weather_data[1,5,10],temp[10,5,1]))

0.9345035129223916
0.9345035129223916
True


---
Problem 5: Combining Transpose with Reshape

Create a 3D array of shape (2, 3, 4).

In [852]:
data = np.random.rand(2, 3, 4)
data.shape

(2, 3, 4)

• First, transpose it to (3, 2, 4).

In [853]:
temp = data.transpose(1,0,2)
temp.shape

(3, 2, 4)

Then reshape the result into a 2D array of shape (6, 4).

In [854]:
reshaped_data = temp.reshape(6,4)

Print both intermediate and final shapes.

In [855]:
print(data.shape)
print(temp.shape)
print(reshaped_data.shape)

(2, 3, 4)
(3, 2, 4)
(6, 4)


Verify that the reshaping preserves the total number of elements.

In [856]:
print(f'total number of ele in original data {np.prod(data.shape)}')
print(f'total number of ele after reshape {np.prod(reshaped_data.shape)}')

total number of ele in original data 24
total number of ele after reshape 24


---
**NumPy Transpose Problems with 3D Arrays (Use
Case Based)**

 **Problem 1: Medical Imaging**

A hospital stores MRI scans in the format(patients, slices, pixels).

Create a NumPy array of shape (2, 4, 5) representing 2 patients, each with 4 slices of size 5
pixels.

In [857]:
patient_data = np.random.rand(2,4,5)
patient_data.shape

(2, 4, 5)

Transpose the data so that the shape becomes (4, 2, 5) → now each slice groups data from both
patients.

In [858]:
transpose_data = patient_data.transpose(1,0,2)
transpose_data.shape

(4, 2, 5)

Verify the new shape and check where element [patient=1, slice=2, pixel=3] is located in the
new layout.

In [859]:
print(patient_data[1,2,3])
print(transpose_data[2,1,3])

0.6296233628536457
0.6296233628536457



**Problem 2: Video Frame**

A video dataset is stored in the format (frames, height, width).
• Create a NumPy array of shape (6, 3, 4) → 6 frames, each with 3x4 pixels.

In [860]:
viddata = np.random.rand(6,3,4)
viddata.shape

(6, 3, 4)

• Transpose it to (3, 4, 6) → now each pixel position shows its value across all frames.

In [861]:
temp = viddata.transpose(1,2,0)
temp.shape

(3, 4, 6)

Verify that frame-wise data is correctly rearranged by checking positions before and after transpose.

In [862]:
print('before transpose ')
print(viddata)
print('----------------------\nafter transpose ')
print(temp)

before transpose 
[[[0.91946478 0.64098286 0.37107076 0.48907233]
  [0.37718177 0.63904563 0.17506008 0.79863094]
  [0.60974734 0.32406199 0.43485858 0.71240575]]

 [[0.12015521 0.17997761 0.70116721 0.91465769]
  [0.38285427 0.43832119 0.64628661 0.18596097]
  [0.17131991 0.84058381 0.44347507 0.52023444]]

 [[0.80814644 0.97756557 0.13894333 0.9850332 ]
  [0.44462943 0.60371811 0.18416484 0.60281011]
  [0.96143966 0.04022949 0.88889374 0.07143542]]

 [[0.65434177 0.60911565 0.150603   0.16531017]
  [0.7767151  0.28202685 0.62464207 0.73891051]
  [0.52227135 0.03244792 0.55011364 0.49490862]]

 [[0.78285546 0.1931445  0.49993252 0.6387521 ]
  [0.83836355 0.75914304 0.24094243 0.39342191]
  [0.90547471 0.93274971 0.63567144 0.91663049]]

 [[0.54814952 0.97672135 0.41797099 0.97590572]
  [0.1274074  0.08959977 0.25914638 0.50757381]
  [0.45929151 0.25333371 0.09948821 0.06416121]]]
----------------------
after transpose 
[[[0.91946478 0.12015521 0.80814644 0.65434177 0.78285546 0.548149

----
**Problem 3: IoT Sensor Data**

A smart building records temperature with 3 sensors every hour for 2 days. Data is stored as (days, hours,sensors)

In [863]:
iot_data = np.random.rand(2,4,3)
iot_data.shape

(2, 4, 3)

Transpose it to (3, 2, 4) so that the first axis corresponds to sensors, making analysis sensor-wise.

In [864]:
transpose_data = iot_data.transpose(2,0,1)
transpose_data.shape

(3, 2, 4)

Verify the mapping of element [day=1, hour=2, sensor=0].

In [865]:
print(iot_data[1,2,0])
print(transpose_data[0,1,2])

0.19380585994404076
0.19380585994404076


---
**Problem 4: Sports Team Performance**

A league records match statistics for 2 teams across 3 matches, tracking 4 performance metrics per match.
Data is stored as (teams, matches, metrics).

Create a NumPy array of shape (2, 3, 4).

In [866]:
sports_data = np.random.rand(2,3,4)
sports_data.shape

(2, 3, 4)

Transpose it to (3, 2, 4) → now each match groups the performance of both teams.

In [867]:
temp = sports_data.transpose(1,0,2)
temp.shape

(3, 2, 4)

Confirm where the stats of Team 1, Match 2, Metric 3 go in the new layout.

In [868]:
print(sports_data[1,2,3])
print(temp[2,1,3])

0.9772951338545455
0.9772951338545455


---
**Problem 5: Climate Data**

A research project stores temperature readings for 2 years, each with 3 months, and 5 cities. Format: (years,
months, cities).

• Create a NumPy array of shape (2, 3, 5).

In [869]:
climate_data = np.random.rand(2,3,5)
climate_data.shape

(2, 3, 5)

Transpose it to (5, 2, 3) → so each city has its own block of data across years and months.

In [870]:
temp = climate_data.transpose(2,0,1)
temp.shape

(5, 2, 3)

Check that the total number of elements remains the same after transpose.

In [871]:
ele_temp = np.prod(temp.shape)
ele_data = np.prod(climate_data.shape)
print('ele in transpose data ',ele_temp)
print('ele in original data ',ele_data)

ele in transpose data  30
ele in original data  30


---
**NumPy Fancy Indexing Problems (1D, 2D, 3D)
1D Array Use Cases**

Problem 1: Stock Prices

Create a 1D NumPy array of 30 stock prices.

In [872]:
stock_price = np.random.rand(30)
stock_price

array([0.2696932 , 0.6462334 , 0.07088051, 0.17609876, 0.04934608,
       0.31598251, 0.81532626, 0.49031276, 0.68956226, 0.63953172,
       0.83402798, 0.10099486, 0.15489681, 0.664444  , 0.09752453,
       0.7055356 , 0.96500871, 0.33050542, 0.93495457, 0.02665502,
       0.80431212, 0.39633198, 0.33288801, 0.55655589, 0.29276186,
       0.61207847, 0.46428858, 0.82634228, 0.44626418, 0.25299519])

Extract the prices on prime-numbered days.

In [873]:
def isPrime(num):
  if num<=1:
    return False
  for i in range(2,int(num**0.5)+1):
    if num%i==0:
      return False
  return True

for i in range(0,len(stock_price)):
  if isPrime(i+1):
    print(f'price on day {i+1} : {stock_price[i]}')

price on day 2 : 0.6462334001395631
price on day 3 : 0.07088050748005781
price on day 5 : 0.0493460752029965
price on day 7 : 0.8153262560942532
price on day 11 : 0.8340279788697377
price on day 13 : 0.15489681387371268
price on day 17 : 0.9650087111747531
price on day 19 : 0.9349545653539063
price on day 23 : 0.3328880120367115
price on day 29 : 0.4462641811389828


Find the top 5 highest prices using fancy indexing.

In [874]:
sorted_stock = np.sort(stock_price)
top_5 = sorted_stock[-6:-1]
for i in range(0,len(top_5)):
  print(f'top {i+1}->{top_5[i]}')

top 1->0.8043121186264164
top 2->0.8153262560942532
top 3->0.8263422766153841
top 4->0.8340279788697377
top 5->0.9349545653539063


---
**Problem 2: Exam Scores**

Generate a 1D array of 50 student scores (0–100).
• Extract the scores of the top 10 students (highest scores).

In [875]:
student_marks = np.array([np.random.randint(0,100) for i in range(20,100)])


Extract the scores of the top 10 students (highest scores).

In [876]:
sorted_marks = np.sort(student_marks)
top_10 = sorted_marks[-11:-1]
for i in range(0,len(top_10)):
  print(f'top {i+1}-> {top_10[i]}')

top 1-> 82
top 2-> 82
top 3-> 82
top 4-> 85
top 5-> 85
top 6-> 86
top 7-> 87
top 8-> 87
top 9-> 88
top 10-> 91


In [877]:
student_marks[student_marks<40]=-1
print(student_marks)

[41 -1 -1 -1 87 -1 -1 88 51 64 40 -1 82 87 58 -1 76 72 -1 74 50 85 85 -1
 50 -1 -1 -1 -1 -1 58 -1 82 41 -1 65 43 -1 -1 86 51 46 -1 -1 57 -1 65 78
 -1 -1 73 57 53 -1 41 43 62 -1 70 91 -1 -1 -1 53 53 40 47 -1 54 96 49 40
 -1 40 82 -1 55 46 67 45]


---
**Problem 3: Sensor Fault Detection**

Create a 1D array of 100 sensor readings (random floats).

• Find all indices where values are above mean + 1 std deviation.

In [878]:
sensor_data = np.random.rand(100)

In [879]:
sensor_std = np.std(sensor_data)
print('standerd deviation ',sensor_std)
sensor_data[sensor_data<sensor_std]=0
print('values above 1 std \n',sensor_data)

standerd deviation  0.2756056656121361
values above 1 std 
 [0.68945559 0.         0.53355978 0.87955569 0.         0.
 0.50922763 0.9079639  0.         0.52678758 0.68591695 0.64980792
 0.         0.         0.38724642 0.2944842  0.95656828 0.84642431
 0.55021354 0.88066449 0.61841425 0.52842909 0.32790322 0.
 0.53620127 0.         0.         0.383119   0.71344998 0.31152583
 0.40132408 0.43032846 0.82456453 0.42352952 0.58790114 0.59685937
 0.         0.66642464 0.66316821 0.30323132 0.56155106 0.
 0.95706732 0.         0.95778361 0.         0.73322543 0.
 0.44154586 0.44696019 0.97681251 0.47733624 0.         0.59096021
 0.48505963 0.74218053 0.         0.72644066 0.80742061 0.46964041
 0.52416696 0.71589071 0.83632682 0.77902002 0.79896349 0.
 0.         0.94488091 0.6381225  0.28147752 0.         0.39134023
 0.84607837 0.68332617 0.         0.82116298 0.49594187 0.
 0.44149325 0.55540378 0.         0.         0.29093814 0.28764474
 0.80578013 0.         0.         0.77744529 0.867

In [880]:

print('sensor data that are above std \n',sensor_data[sensor_data!=0])

sensor data that are above std 
 [0.68945559 0.53355978 0.87955569 0.50922763 0.9079639  0.52678758
 0.68591695 0.64980792 0.38724642 0.2944842  0.95656828 0.84642431
 0.55021354 0.88066449 0.61841425 0.52842909 0.32790322 0.53620127
 0.383119   0.71344998 0.31152583 0.40132408 0.43032846 0.82456453
 0.42352952 0.58790114 0.59685937 0.66642464 0.66316821 0.30323132
 0.56155106 0.95706732 0.95778361 0.73322543 0.44154586 0.44696019
 0.97681251 0.47733624 0.59096021 0.48505963 0.74218053 0.72644066
 0.80742061 0.46964041 0.52416696 0.71589071 0.83632682 0.77902002
 0.79896349 0.94488091 0.6381225  0.28147752 0.39134023 0.84607837
 0.68332617 0.82116298 0.49594187 0.44149325 0.55540378 0.29093814
 0.28764474 0.80578013 0.77744529 0.86721934 0.27990627 0.89108847
 0.4219728  0.78036483 0.7991447  0.32818259 0.9689384  0.69583811]


---
**Problem 4: DNA Sequence Encoding**

Represent a DNA sequence (A=0, C=1, G=2, T=3) as a 1D NumPy array of length 20.

• Extract all occurrences of G and T.

In [881]:
dna_data = np.array([np.random.randint(0,4) for i in range(0,20)])
dna_data

array([1, 3, 3, 3, 3, 0, 1, 2, 3, 3, 2, 2, 3, 0, 3, 2, 0, 0, 3, 0])

• Extract all occurrences of G and T.

In [882]:
gt = dna_data[dna_data>1]
gt

array([3, 3, 3, 3, 2, 3, 3, 2, 2, 3, 3, 2, 3])

• Replace all A with -1 using fancy indexing.

In [883]:
dna_data[dna_data==0]=-1
dna_data

array([ 1,  3,  3,  3,  3, -1,  1,  2,  3,  3,  2,  2,  3, -1,  3,  2, -1,
       -1,  3, -1])

---
**Problem 5: Employee Salaries**

Create a 1D array of 20 salaries.

In [884]:
salaries_data = np.array([np.random.randint(10000,100000) for i in range(0,20)])

Extract salaries of employees whose index is in [2, 5, 7, 11, 15].

In [885]:
salaries_data[[2, 5, 7, 11, 15]]

array([38663, 89568, 98106, 64316, 78410])

Give a 10% raise only to these extracted salaries using fancy indexing.

In [886]:
salaries_data[[2, 5, 7, 11, 15]] = salaries_data[[2, 5, 7, 11, 15]]*1.1
salaries_data[[2, 5, 7, 11, 15]]

array([ 42529,  98524, 107916,  70747,  86251])

---
**2D Array Use Cases
Problem 6: Matrix Row/Column Extraction**

Create a 6x6 matrix of integers from 1 to 36.

In [887]:
data = np.random.randint(1,36,size=(6,6))
data

array([[ 8,  6, 20, 16, 33, 17],
       [ 3,  6,  1,  1,  4, 23],
       [ 4, 20,  2, 22, 19,  2],
       [25,  5, 11, 19, 10, 34],
       [23, 11, 12, 23, 16, 28],
       [30, 10,  3,  4,  2, 14]])

Extract all elements from rows [1, 3, 5] and columns [0, 2, 4] using fancy indexing.

In [888]:
data[[1,3,5],[0,2,4]]

array([ 3, 11,  2])

---
**Problem 7: Student Marks Table**

Generate a 10x5 array representing 10 students and 5 subjects.

In [889]:
data = np.random.randint(0,100,size=(10,5))
data.shape

(10, 5)

• Extract marks of students [2, 4, 6, 8] in subjects [1, 3].

In [890]:
data[np.ix_([2,4,6,8],[1,3])]

array([[38,  0],
       [ 3,  1],
       [98, 33],
       [33, 84]])

Replace all marks below 30 with 0 for these students.

In [891]:
data[data<30]=0
data

array([[ 0, 97,  0, 48, 89],
       [30,  0, 46, 86, 54],
       [40, 38, 41,  0,  0],
       [ 0,  0, 53, 43, 57],
       [ 0,  0,  0,  0, 62],
       [ 0, 99, 83,  0, 68],
       [ 0, 98, 46, 33, 55],
       [ 0, 44,  0, 45,  0],
       [60, 33, 89, 84, 92],
       [66, 42, 88, 61, 39]])

---
**Problem 8: Airline Seat Booking**

Create a 12x6 seating matrix (rows × columns).

In [892]:
data = np.random.randint(0,2,size=(12,6))
data.shape

(12, 6)

In [893]:
data

array([[1, 1, 0, 1, 1, 0],
       [1, 0, 0, 0, 1, 1],
       [0, 0, 1, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 1, 0],
       [1, 0, 1, 1, 0, 0],
       [1, 0, 1, 0, 1, 1]])

• Extract all aisle seats (first and last column).

In [894]:
data[:,[0,-1]]

array([[1, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 0],
       [1, 1]])

Mark seats [row=2, cols=[1,2,4]] as booked (-1) using fancy indexing.

In [895]:
result = data[2,[1,2,4]]
result

array([0, 1, 0])

---
**Problem 9: Chessboard Pattern**

Create an 8x8 matrix with values from 0–63.

In [896]:
data = np.random.randint(0,36,size=(8,8))
data

array([[31,  6,  8, 17, 25, 13, 20,  8],
       [13,  3, 30,  9,  7, 25,  8, 19],
       [ 4,  8, 15, 29,  3, 24, 18, 14],
       [28, 29, 18, 18, 16, 15, 31, 34],
       [15,  2, 18, 31, 15, 20, 16,  7],
       [28, 15, 28, 22, 17,  3, 21, 18],
       [28,  1, 14, 31, 29, 17, 26, 30],
       [ 4, 31,  1,  0, 12,  0, 22, 17]])

Extract all black squares (even row + odd column, odd row + even column).

In [897]:
temp = data[np.ix_([1,3,5,7],[0,2,4,6])]
temp

array([[13, 30,  7,  8],
       [28, 18, 16, 31],
       [28, 28, 17, 21],
       [ 4,  1, 12, 22]])

In [898]:
data[np.ix_([0,2,4,6],[1,3,5,7])] = -1
data

array([[31, -1,  8, -1, 25, -1, 20, -1],
       [13,  3, 30,  9,  7, 25,  8, 19],
       [ 4, -1, 15, -1,  3, -1, 18, -1],
       [28, 29, 18, 18, 16, 15, 31, 34],
       [15, -1, 18, -1, 15, -1, 16, -1],
       [28, 15, 28, 22, 17,  3, 21, 18],
       [28, -1, 14, -1, 29, -1, 26, -1],
       [ 4, 31,  1,  0, 12,  0, 22, 17]])

---
**Problem 10: Product Sales Data**

Create a 5x7 array representing sales of 5 products over 7 days.

In [899]:
data = np.random.randint(100,1000,size=(5,7))
data

array([[781, 306, 982, 420, 826, 247, 404],
       [721, 260, 517, 144, 521, 782, 769],
       [935, 985, 337, 278, 102, 738, 493],
       [601, 800, 466, 287, 569, 723, 357],
       [171, 724, 670, 746, 993, 693, 197]])

Extract sales of products [1, 3] on days [2, 4, 6].

In [900]:
data[np.ix_([1,2],[2,4,6])]

array([[517, 521, 769],
       [337, 102, 493]])

Increase those extracted values by 20%.

In [901]:
data[np.ix_([1,2],[2,4,6])] = (data[np.ix_([1,2],[2,4,6])] *2.2).astype(int)
data

array([[ 781,  306,  982,  420,  826,  247,  404],
       [ 721,  260, 1137,  144, 1146,  782, 1691],
       [ 935,  985,  741,  278,  224,  738, 1084],
       [ 601,  800,  466,  287,  569,  723,  357],
       [ 171,  724,  670,  746,  993,  693,  197]])

---
**3D Array Use Cases**

**Problem 11:
Video Frames (RGB)**

Create a 4x3x3 array representing 4 frames, each 3x3 pixel.

In [902]:
data = np.random.randint(0,10,size=(4,3,3))
data

array([[[8, 4, 8],
        [0, 9, 6],
        [4, 2, 7]],

       [[3, 9, 9],
        [4, 3, 4],
        [5, 3, 4]],

       [[9, 9, 9],
        [1, 3, 1],
        [7, 0, 0]],

       [[5, 7, 1],
        [2, 8, 2],
        [1, 7, 0]]])

Extract the center pixel from each frame using fancy indexing.

In [903]:
data[:,1,1]

array([9, 3, 3, 8])

---
**Problem 12: Weather Data**

Create a (2, 12, 30) array → 2 years, 12 months, 30 days.

In [904]:
data = np.random.randint(0,10,size=(2,12,30))
data.shape


(2, 12, 30)

Extract temperatures of months [0, 5, 11] for year 1 on days [10, 20].

In [905]:
data[np.ix_([0],[0,5,11],[10,20])]

array([[[7, 3],
        [3, 1],
        [7, 2]]])

---
**Problem 13: Hospital Patient Records**

Create a (3, 4, 5) array → 3 patients, 4 days, 5 test results/day.


In [906]:
data = np.random.randint(1,30,size=(3,4,5))
data

array([[[20,  5, 16, 26, 17],
        [23, 29, 19, 20, 21],
        [28, 13, 21, 22, 10],
        [22, 26, 21,  3, 19]],

       [[20, 14, 27,  9, 11],
        [ 9, 28,  4, 12,  5],
        [ 4, 17, 19, 12, 11],
        [21,  3, 12, 20, 28]],

       [[26,  8, 19,  1, 14],
        [14,  1,  5, 11, 18],
        [25,  4, 25, 19,  4],
        [ 6, 26,  7, 19, 13]]])


• Extract test results of patients [0, 2] on day 3 for tests [1, 3].

In [907]:
ans = data[np.ix_([0,2],[2],[0,2])]
ans

array([[[28, 21]],

       [[25, 25]]])

---
**Problem 14: Sports Team Analytics**

Create a (5, 6, 4) array → 5 teams, 6 matches, 4 stats each.

In [908]:
data = np.random.randint(10,30,size=(5,6,4))
data

array([[[28, 13, 26, 19],
        [18, 13, 22, 24],
        [27, 22, 12, 11],
        [14, 20, 10, 27],
        [11, 12, 29, 28],
        [16, 13, 15, 16]],

       [[18, 11, 23, 22],
        [25, 10, 17, 21],
        [13, 24, 28, 19],
        [15, 22, 23, 27],
        [19, 10, 17, 19],
        [19, 19, 10, 29]],

       [[29, 26, 22, 13],
        [27, 29, 13, 22],
        [21, 23, 28, 22],
        [10, 23, 22, 18],
        [15, 22, 20, 23],
        [25, 20, 22, 28]],

       [[23, 15, 15, 11],
        [21, 15, 26, 25],
        [16, 20, 17, 26],
        [26, 24, 26, 20],
        [12, 11, 27, 28],
        [17, 25, 15, 13]],

       [[21, 19, 26, 11],
        [24, 25, 24, 16],
        [19, 16, 29, 12],
        [24, 24, 22, 25],
        [24, 27, 15, 13],
        [28, 12, 20, 27]]])

• Extract stats of teams [1, 3, 4] for matches [2, 5].

In [909]:
data[np.ix_([0,2,3],[1,4])]

array([[[18, 13, 22, 24],
        [11, 12, 29, 28]],

       [[27, 29, 13, 22],
        [15, 22, 20, 23]],

       [[21, 15, 26, 25],
        [12, 11, 27, 28]]])

---
**Problem 15: Movie Ratings**

Create a (10, 5, 4) array → 10 movies, 5 critics, 4 rating categories.

In [910]:
data = np.random.randint(10,30,size=(10,5,4))
data

array([[[17, 18, 12, 18],
        [13, 20, 17, 25],
        [12, 27, 10, 19],
        [12, 10, 11, 12],
        [29, 15, 23, 11]],

       [[12, 13, 16, 22],
        [23, 13, 20, 19],
        [29, 23, 10, 17],
        [24, 24, 18, 11],
        [12, 26, 12, 24]],

       [[14, 26, 23, 15],
        [11, 11, 29, 18],
        [16, 11, 14, 11],
        [27, 21, 19, 12],
        [17, 19, 23, 16]],

       [[22, 29, 11, 17],
        [27, 11, 19, 10],
        [19, 11, 22, 22],
        [15, 12, 29, 19],
        [29, 26, 11, 13]],

       [[21, 17, 15, 25],
        [29, 27, 18, 19],
        [18, 18, 13, 29],
        [12, 14, 22, 15],
        [19, 29, 26, 17]],

       [[11, 27, 28, 18],
        [12, 28, 23, 13],
        [16, 26, 18, 24],
        [10, 21, 15, 12],
        [11, 18, 13, 19]],

       [[22, 13, 22, 24],
        [23, 25, 17, 14],
        [11, 19, 13, 22],
        [26, 17, 24, 26],
        [19, 29, 12, 21]],

       [[24, 27, 16, 19],
        [20, 12, 19, 17],
        [28, 17, 14, 10]

Extract ratings of movies [2, 4, 7] by critics [1, 3] in categories [0, 2].

In [911]:
data[np.ix_([2,4,7],[1,3],[0,2])]

array([[[11, 29],
        [27, 19]],

       [[29, 18],
        [12, 22]],

       [[20, 19],
        [22, 25]]])

---
**Problem 16: IoT Device Monitoring**

Create a (3, 24, 7) array → 3 devices, 24 hours, 7 days.

In [912]:
data = np.random.randint(10,30,size=(3,24,7))
data

array([[[10, 25, 28, 14, 28, 25, 16],
        [17, 21, 26, 11, 16, 16, 11],
        [15, 15, 14, 25, 26, 24, 29],
        [18, 28, 26, 28, 25, 16, 16],
        [13, 27, 29, 26, 24, 25, 27],
        [21, 23, 13, 19, 10, 10, 24],
        [25, 26, 22, 12, 27, 26, 20],
        [24, 12, 26, 22, 28, 21, 24],
        [12, 13, 13, 24, 21, 13, 28],
        [21, 12, 13, 16, 19, 14, 19],
        [15, 25, 19, 12, 26, 25, 24],
        [19, 10, 14, 18, 28, 23, 23],
        [19, 27, 10, 20, 21, 11, 12],
        [29, 29, 27, 23, 13, 28, 23],
        [20, 23, 13, 15, 15, 27, 15],
        [26, 24, 24, 13, 13, 18, 27],
        [16, 13, 12, 10, 25, 17, 18],
        [26, 27, 22, 11, 18, 29, 16],
        [21, 11, 27, 12, 11, 25, 26],
        [25, 20, 23, 20, 29, 10, 17],
        [18, 22, 28, 27, 22, 21, 16],
        [19, 17, 28, 29, 22, 26, 26],
        [16, 10, 18, 28, 26, 18, 27],
        [23, 28, 10, 29, 12, 18, 22]],

       [[19, 25, 26, 20, 22, 12, 12],
        [28, 15, 24, 20, 11, 28, 24],
        [1

• Extract hourly readings for devices [0, 2] on days [1, 3, 5].

In [913]:
data[np.ix_([0,2],np.arange(data.shape[1]),[1,3,5])]

array([[[25, 14, 25],
        [21, 11, 16],
        [15, 25, 24],
        [28, 28, 16],
        [27, 26, 25],
        [23, 19, 10],
        [26, 12, 26],
        [12, 22, 21],
        [13, 24, 13],
        [12, 16, 14],
        [25, 12, 25],
        [10, 18, 23],
        [27, 20, 11],
        [29, 23, 28],
        [23, 15, 27],
        [24, 13, 18],
        [13, 10, 17],
        [27, 11, 29],
        [11, 12, 25],
        [20, 20, 10],
        [22, 27, 21],
        [17, 29, 26],
        [10, 28, 18],
        [28, 29, 18]],

       [[26, 14, 28],
        [12, 29, 13],
        [22, 11, 10],
        [19, 21, 13],
        [12, 29, 13],
        [27, 17, 15],
        [14, 16, 16],
        [10, 25, 26],
        [10, 22, 12],
        [26, 26, 22],
        [20, 16, 24],
        [28, 18, 26],
        [12, 25, 27],
        [29, 25, 27],
        [13, 28, 10],
        [19, 19, 19],
        [25, 10, 28],
        [26, 24, 27],
        [12, 22, 19],
        [15, 12, 20],
        [21, 24, 24],
        

---
**Problem 17: Retail Store Inventory**

Create a (4, 10, 6) array → 4 stores, 10 products, 6 months.


In [914]:
data = np.random.randint(10,30,size=(4,10,6))
data

array([[[20, 16, 24, 20, 16, 24],
        [16, 12, 24, 21, 19, 22],
        [13, 27, 26, 27, 18, 22],
        [21, 20, 19, 13, 23, 13],
        [23, 26, 22, 14, 13, 25],
        [28, 15, 29, 14, 25, 15],
        [16, 29, 28, 29, 28, 23],
        [10, 29, 15, 20, 12, 11],
        [17, 24, 28, 14, 14, 20],
        [29, 14, 16, 13, 10, 13]],

       [[23, 28, 19, 22, 29, 14],
        [21, 11, 23, 26, 10, 11],
        [15, 18, 15, 16, 19, 23],
        [17, 23, 17, 21, 25, 19],
        [28, 19, 18, 23, 23, 10],
        [26, 23, 12, 15, 14, 15],
        [11, 25, 11, 29, 11, 19],
        [21, 17, 18, 15, 15, 23],
        [18, 29, 14, 24, 22, 19],
        [27, 11, 17, 13, 14, 26]],

       [[22, 16, 11, 10, 23, 20],
        [23, 15, 23, 28, 14, 28],
        [11, 19, 19, 21, 27, 14],
        [12, 15, 22, 12, 16, 18],
        [19, 25, 21, 12, 11, 20],
        [26, 28, 28, 27, 22, 13],
        [22, 10, 28, 29, 15, 27],
        [21, 17, 25, 10, 23, 13],
        [13, 18, 17, 21, 18, 26],
        [2

Extract data for stores [1, 3], products [2, 5, 7], and months [0, 2, 4].

In [915]:
data[np.ix_([1,3],[2,5,7],[0,2,4])]

array([[[15, 15, 19],
        [26, 12, 14],
        [21, 18, 15]],

       [[12, 18, 14],
        [17, 29, 19],
        [23, 16, 17]]])

---
**Problem 18: Scientific Experiment**

Create a (2, 5, 8) array → 2 trials, 5 experiments, 8 observations each.


In [916]:
data = np.random.randint(10,30,size=(2,5,8))
data

array([[[23, 13, 27, 11, 14, 12, 15, 18],
        [10, 11, 15, 28, 22, 21, 21, 18],
        [11, 19, 14, 13, 14, 18, 27, 11],
        [12, 14, 21, 11, 18, 20, 16, 13],
        [20, 10, 13, 21, 18, 22, 15, 13]],

       [[14, 11, 21, 28, 27, 14, 17, 25],
        [18, 11, 16, 19, 25, 28, 13, 13],
        [15, 11, 10, 28, 15, 21, 18, 18],
        [21, 10, 25, 11, 17, 25, 15, 26],
        [28, 12, 19, 12, 13, 22, 29, 22]]])

Extract trial 1 results for experiments [1, 4] at observations [2, 5, 7].

In [917]:
data[np.ix_(np.arange(data.shape[0]),[1,4],[2,5,7])]

array([[[15, 21, 18],
        [13, 22, 13]],

       [[16, 28, 13],
        [19, 22, 22]]])

---
**Problem 19: E-commerce Orders**

Create a (6, 4, 3) array → 6 customers, 4 orders each, 3 features/order.

In [918]:
data = np.random.randint(10,30,size=(6,4,3))
data

array([[[26, 24, 12],
        [19, 23, 27],
        [25, 19, 25],
        [23, 15, 12]],

       [[29, 11, 16],
        [25, 20, 25],
        [28, 20, 27],
        [26, 12, 23]],

       [[16, 17, 23],
        [15, 22, 10],
        [15, 25, 18],
        [21, 10, 19]],

       [[11, 14, 27],
        [29, 24, 11],
        [12, 16, 19],
        [19, 13, 13]],

       [[17, 10, 28],
        [18, 21, 10],
        [13, 27, 26],
        [29, 29, 25]],

       [[12, 12, 19],
        [22, 13, 27],
        [28, 28, 12],
        [16, 22, 17]]])

Extract features of customers [0, 2, 5] for orders [1, 3].

In [919]:
data[np.ix_([0,2,5],np.arange(data.shape[1]),[0,2])]

array([[[26, 12],
        [19, 27],
        [25, 25],
        [23, 12]],

       [[16, 23],
        [15, 10],
        [15, 18],
        [21, 19]],

       [[12, 19],
        [22, 27],
        [28, 12],
        [16, 17]]])

---
**Problem 20: Image Dataset**

Create a (5, 28, 28) array → 5 grayscale images of 28×28 pixels.

In [920]:
data = np.random.randint(10,30,size=(2,28,28))
data

array([[[10, 19, 13, ..., 14, 20, 19],
        [15, 18, 11, ..., 27, 26, 18],
        [14, 19, 10, ..., 28, 19, 16],
        ...,
        [11, 23, 10, ..., 14, 13, 28],
        [10, 26, 27, ..., 10, 25, 26],
        [19, 10, 20, ..., 12, 23, 29]],

       [[12, 14, 25, ..., 17, 19, 17],
        [17, 12, 21, ..., 15, 23, 23],
        [26, 17, 13, ..., 14, 26, 12],
        ...,
        [10, 20, 12, ..., 15, 26, 22],
        [21, 12, 29, ..., 23, 22, 19],
        [20, 29, 15, ..., 10, 10, 28]]])

Extract the corner pixels (top-left, top-right, bottom-left, bottom-right) from each image using fancy
indexing.

In [921]:
data.shape[0]

2

In [922]:
data[np.ix_(
    np.arange(data.shape[0]),
     [0,data.shape[1]-1],
      [0,data.shape[2]-1])]

array([[[10, 19],
        [19, 29]],

       [[12, 17],
        [20, 28]]])

---
**Detective Case Study: The Mystery of the Stolen
Diamonds**

**Scene 1: The Crime Scene**

Detective Arjun Mehta arrives at a jewelry store in Mumbai where diamonds have been stolen.
The store CCTV captured 100 frames of data, each containing sensor readings.

• Create a 1D NumPy array of 100 integers (0–9) representing sensor triggers.

In [923]:
data = np.random.randint(0,9,size=(100))
data

array([6, 3, 2, 5, 8, 1, 7, 7, 2, 7, 2, 2, 0, 0, 7, 3, 7, 8, 8, 1, 0, 2,
       5, 1, 2, 4, 4, 4, 1, 0, 0, 2, 4, 0, 0, 6, 5, 6, 5, 7, 2, 1, 2, 6,
       4, 4, 2, 2, 2, 3, 2, 2, 6, 4, 6, 5, 5, 8, 8, 7, 0, 0, 3, 6, 1, 6,
       3, 4, 0, 0, 7, 8, 4, 2, 3, 2, 0, 7, 3, 8, 4, 3, 3, 4, 2, 0, 8, 6,
       4, 7, 4, 5, 0, 1, 0, 2, 0, 3, 1, 0])

• Find out how many times the sensor detected activity (value > 5).

In [924]:
len(data[data>5])

27

---
**Scene 2: Suspect List**

Inspector Rani Sharma provides a list of 20 suspects with their ages.
Ages are randomly assigned.

Task:
• Create a 1D array of 20 ages.

In [925]:
data = np.random.randint(0,85,size=(20))
data

array([24, 22, 60, 53, 16, 33,  8, 14, 69, 56, 64, 19, 12, 42, 78, 51,  4,
       47, 28, 35])

Use fancy indexing to extract the ages of suspects with even indices.

In [926]:
evenIndex = [i+1 for i in range(0,len(data)) if i%2==0]
data[evenIndex]

array([22, 53, 33, 14, 56, 19, 42, 51, 47, 35])

Find the youngest and oldest suspects.

In [927]:
print('highest age ',data.max())
print('youngest age ',data.min())

highest age  78
youngest age  4


---
**Scene 3: Witness Statement**

A witness says: “I saw 5 people entering the store in pairs.”

CCTV logs show movements stored as a 10x2 matrix (10 rows, 2 values each: entry time and exit time).

Task:
• Create a 2D NumPy array of shape (10, 2) representing entry and exit times.

In [928]:
data = np.random.randint(10,40,size=(10,2))
data

array([[20, 36],
       [26, 33],
       [13, 19],
       [27, 28],
       [37, 19],
       [38, 39],
       [39, 38],
       [30, 38],
       [30, 19],
       [36, 26]])

• Find the average entry time.

In [929]:
np.mean(data[:,0])

np.float64(29.6)

Extract all rows where exit time < entry time + 5 minutes (suspicious quick visits).

In [930]:
data[data[:,0]<data[:,1]+5]

array([[20, 36],
       [26, 33],
       [13, 19],
       [27, 28],
       [38, 39],
       [39, 38],
       [30, 38]])

---
**Scene 4: Car Parking Data**

Outside the store, parking lot cameras recorded cars over 7 days and 5 time slots per day.

Task:
• Create a 2D array of shape (7, 5) representing number of cars.

In [931]:
data = np.random.randint(10,50,size=(7,5))
data

array([[20, 44, 27, 11, 31],
       [45, 47, 26, 29, 37],
       [14, 13, 22, 44, 44],
       [36, 25, 26, 16, 14],
       [17, 18, 11, 42, 36],
       [45, 25, 34, 18, 43],
       [40, 15, 46, 47, 41]])

Find the day with maximum car traffic.

In [932]:
sumarray = np.sum(data,axis=1)
print('day whith max traffic :',sumarray.argmax())

day whith max traffic : 6


Extract car counts for days [2, 4, 6] and time slots [1, 3] using fancy indexing.

In [933]:
data[np.ix_([2,4,6],[1,3])]

array([[13, 44],
       [18, 42],
       [15, 47]])

---
**Scene 5: Suspect Movements**

Detective Arjun obtains GPS coordinates of 3 suspects over 4 days, with 2 readings/day.
Task:

• Create a 3D array of shape (3, 4, 2) → (suspects, days, coordinates).


In [934]:
data = np.random.randint(10,50,size=(3,4,5))
data

array([[[41, 16, 11, 20, 47],
        [39, 41, 37, 17, 19],
        [38, 38, 14, 38, 48],
        [17, 14, 38, 21, 47]],

       [[15, 18, 43, 49, 34],
        [25, 14, 14, 25, 22],
        [39, 32, 29, 16, 10],
        [40, 24, 41, 45, 17]],

       [[41, 12, 44, 33, 25],
        [30, 33, 27, 38, 45],
        [44, 42, 13, 25, 23],
        [23, 38, 49, 34, 44]]])

Transpose it to (4, 3, 2) to compare suspects day-wise.

In [935]:
transpose_data = data.transpose(1,0,2)
transpose_data

array([[[41, 16, 11, 20, 47],
        [15, 18, 43, 49, 34],
        [41, 12, 44, 33, 25]],

       [[39, 41, 37, 17, 19],
        [25, 14, 14, 25, 22],
        [30, 33, 27, 38, 45]],

       [[38, 38, 14, 38, 48],
        [39, 32, 29, 16, 10],
        [44, 42, 13, 25, 23]],

       [[17, 14, 38, 21, 47],
        [40, 24, 41, 45, 17],
        [23, 38, 49, 34, 44]]])

Extract locations of suspect 2 on days [1, 3].

In [936]:
transpose_data[np.ix_([1,3],[2],np.arange(transpose_data.shape[2]))]

array([[[30, 33, 27, 38, 45]],

       [[23, 38, 49, 34, 44]]])

----
**Scene 6: Hidden Transactions**

Rani uncovers financial records of 5 suspects, each with 6 months of transactions.

Task:

Create a 2D array of shape (5, 6).

In [937]:
data = np.random.randint(10000,80000,size=(5,6))
data

array([[67593, 56445, 16868, 33191, 21548, 73447],
       [69924, 21438, 57265, 64890, 44025, 61875],
       [54656, 23022, 35063, 46693, 42799, 55322],
       [61375, 50706, 45642, 68216, 74163, 44559],
       [35061, 56291, 72545, 12413, 37654, 17978]])

Find suspects whose average monthly spending > 50,000.

In [938]:
indecis = np.where(np.mean(data,axis=1)>50000)[0]
print("suspects : ",indecis)

suspects :  [1 3]


Extract transactions of suspects [1, 3] in months [2, 4].

In [939]:
data[np.ix_([1,3],[2,4])]

array([[57265, 44025],
       [45642, 74163]])

---
**Scene 7: Fingerprint Evidence**

At the scene, police collected 3 fingerprint scans, each stored as a 4x4 pixel grayscale image.

Task:

• Create a 3D array of shape (3, 4, 4).

In [940]:
data = np.random.randint(0,500,size=(3,4,4))
data


array([[[  2, 193, 163, 136],
        [499, 472, 327, 428],
        [185, 168, 232, 478],
        [420, 125, 487, 456]],

       [[190, 243,  91, 438],
        [349, 464,  46,  75],
        [139, 492, 403,  39],
        [ 27, 388, 416, 184]],

       [[453, 456, 157,  63],
        [478, 429, 477, 446],
        [ 93, 354, 462, 492],
        [230,  99, 205, 290]]])

• Extract the center 2x2 region of each image.

In [941]:
data[np.ix_(np.arange(data.shape[0]),[1,2],[1,2])]

array([[[472, 327],
        [168, 232]],

       [[464,  46],
        [492, 403]],

       [[429, 477],
        [354, 462]]])

Replace all pixel values < 100 with 0 (noise removal).

In [942]:
data[data<100]=-1
data

array([[[ -1, 193, 163, 136],
        [499, 472, 327, 428],
        [185, 168, 232, 478],
        [420, 125, 487, 456]],

       [[190, 243,  -1, 438],
        [349, 464,  -1,  -1],
        [139, 492, 403,  -1],
        [ -1, 388, 416, 184]],

       [[453, 456, 157,  -1],
        [478, 429, 477, 446],
        [ -1, 354, 462, 492],
        [230,  -1, 205, 290]]])

---
**Scene 8: Decoding the Cipher**

The thieves left a coded message as numbers [65, 66, 67, 68, 69].
It maps to ASCII letters.

Task:
• Create a 1D array of ASCII values.


In [943]:
code = np.array([65,66,67,68,69])
data = np.arange(65,91)
data

array([65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
       82, 83, 84, 85, 86, 87, 88, 89, 90])

In [944]:
data = np.vectorize(chr)(data)
data

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
      dtype='<U1')

In [945]:
code = np.vectorize(chr)(code)
code

array(['A', 'B', 'C', 'D', 'E'], dtype='<U1')

---

**Scene 9: Narrowing the Suspects**

Based on data, only 4 suspects remain.
Their data includes height, weight, and age, stored in a 4x3 matrix.

Task:
• Create the array and label columns as [Height, Weight, Age]

In [946]:
data = np.array(
      [[65, 76, 24],
       [53, 26, 47],
       [30, 24, 25],
       [77, 83, 38]])

In [947]:
import pandas as pd

df = pd.DataFrame(data,columns=['Height','Weight','Age'])
df

Height  Weight  Age
0      65      76   24
1      53      26   47
2      30      24   25
3      77      83   38

• Extract suspects with weight > 70 and age < 30.

In [948]:
data[(data[:,1]>70) & (data[:,-1]<30)]

array([[65, 76, 24]])

---
**Scene 10: The Final Chase**

CCTV confirms that 2 cars were used in the escape, tracked every 3 hours for 2 days.

Task:
• Create a 3D array of shape (2, 2, 8) → (cars, days, 8 time slots).

In [949]:
data = np.array(
    [[[7, 1, 7, 2, 5, 7, 5, 7],
        [3, 4, 4, 4, 3, 4, 1, 9]],

       [[6, 1, 2, 1, 8, 7, 7, 6],
        [1, 4, 2, 3, 6, 4, 6, 3]]])
temp = data.transpose(0,2,1)
temp.shape
ans = []
for i in range(temp.shape[1]):
  if np.array_equal(temp[0,i],temp[1,i]):
    ans.append(temp[0,i])
ans

[array([1, 4]), array([7, 4])]

 Transpose it to (2, 8, 2) → (cars, time slots, days).

In [950]:
temp = data.transpose(0,2,1)
temp.shape

(2, 8, 2)

Find at which time slot both cars were parked at the same location

In [951]:
ans = []
for i in range(temp.shape[1]):
  if np.array_equal(temp[0,i],temp[1,i]):
    ans.append(temp[0,i])
ans

[array([1, 4]), array([7, 4])]

**Detective Story:** **The Mystery of the Stolen Diamonds**

**Author: Detective Training Exercise**

**Goal: Practice all major NumPy operations through a fun mystery case**.


In [952]:
import numpy as np
print("️ Scene 1: The Crime Scene")
print("Detective Arjun Mehta arrives at a jewelry store in Mumbai. Diamonds have been stolen!")
print("The CCTV captured 100 sensor readings (values 0–9).")
sensor_data = np.random.randint(0, 10, size=100)
high_activity_count = sum(sensor_data>7)
print("\nScene 1 Result → High activity count:",high_activity_count)

️ Scene 1: The Crime Scene
Detective Arjun Mehta arrives at a jewelry store in Mumbai. Diamonds have been stolen!
The CCTV captured 100 sensor readings (values 0–9).

Scene 1 Result → High activity count: 24


In [953]:
print("\n Scene 2: Suspect List\n")
print("Inspector Rani Sharma provides a list of 20 suspects with their ages.")
ages = np.random.randint(18, 60, size=20)
even_index_ages = [i for i in range(1,len(ages)+1) if i%2==0]
print('age in even index ',even_index_ages)
oldest = ages.max()
youngest = ages.min()
print("\nScene 2 Result → Youngest:", youngest, "Oldest:",oldest)


 Scene 2: Suspect List

Inspector Rani Sharma provides a list of 20 suspects with their ages.
age in even index  [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

Scene 2 Result → Youngest: 19 Oldest: 59


---

In [954]:
print("\n Scene 3: Witness Statement")
print("Witness says: 'I saw 5 people entering the store in pairs.'")
print("CCTV logs are stored as a 10x2 matrix (entry, exit times).")
cctv_logs = np.random.randint(0, 24, size=(10, 2))




 Scene 3: Witness Statement
Witness says: 'I saw 5 people entering the store in pairs.'
CCTV logs are stored as a 10x2 matrix (entry, exit times).


In [955]:
avg_entry = np.mean(cctv_logs[:,0])
print('avg_entry =',avg_entry)
quick_visits = cctv_logs[cctv_logs[:,1]< (cctv_logs[:,0]+5)]
print("\nScene 3 Result → Suspicious visits:\n",quick_visits)

avg_entry = 10.6

Scene 3 Result → Suspicious visits:
 [[13 12]
 [14  3]
 [10 10]
 [14  8]
 [10 14]]


---

In [956]:
print("\n Scene 4: Car Parking Data")
print("Parking lot cameras recorded cars for 7 days, 5 time slots each.")
cars = np.random.randint(0, 20, size=(7, 5))


 Scene 4: Car Parking Data
Parking lot cameras recorded cars for 7 days, 5 time slots each.


In [957]:
day_sum=cars.sum(axis=1)
max_day = day_sum.max()

**TODO: Extract traffic for days [2,4,6] and time slots [1,3]**


In [958]:
subset_traffic = cars[np.ix_([2,4,6],[1,3])]
print("\nScene 4 Result → Max traffic day:",subset_traffic)



Scene 4 Result → Max traffic day: [[ 4 13]
 [15 12]
 [13  9]]


---

In [959]:
print("\n Scene 5: Suspect Movements")
print("GPS coordinates of 3 suspects, 4 days, 2 coords/day.")
gps = np.random.randint(0, 100, size=(3, 4, 2))


 Scene 5: Suspect Movements
GPS coordinates of 3 suspects, 4 days, 2 coords/day.


TODO: Transpose to (4,3,2)

In [960]:
gps_transposed = gps.transpose(1,0,2)
gps_transposed

array([[[23, 91],
        [24, 27],
        [95, 29]],

       [[92,  3],
        [10, 19],
        [83, 71]],

       [[79, 26],
        [52,  5],
        [51,  5]],

       [[16, 53],
        [38,  6],
        [ 2, 71]]])

TODO: Extract suspect 2 on days [1,3]

In [961]:
suspect2_movements = gps_transposed[np.ix_(
    [1,3],
     [2],
    np.arange(gps_transposed.shape[2])
    )]
print("\nScene 5 Result → Movements of suspect 2:\n",suspect2_movements)


Scene 5 Result → Movements of suspect 2:
 [[[83 71]]

 [[ 2 71]]]


---

In [962]:
print("\n️ Scene 6: Hidden Transactions")
print("Financial records of 5 suspects, 6 months.")
transactions = np.random.randint(20000, 100000, size=(5, 6))
transactions


️ Scene 6: Hidden Transactions
Financial records of 5 suspects, 6 months.


array([[77733, 46699, 45316, 81050, 75325, 71103],
       [86019, 57136, 22473, 64685, 94362, 97955],
       [84537, 28935, 27585, 65548, 31333, 88100],
       [21352, 71161, 96196, 63327, 33530, 76241],
       [77090, 60611, 74223, 60225, 21509, 72106]])

TODO: Find suspects with avg spending > 50,000

In [963]:
big_spenders = transactions[transactions.mean(axis=1)>50000,:]
print("\nScene 6 Result → Big spenders:\n", big_spenders)


Scene 6 Result → Big spenders:
 [[77733 46699 45316 81050 75325 71103]
 [86019 57136 22473 64685 94362 97955]
 [84537 28935 27585 65548 31333 88100]
 [21352 71161 96196 63327 33530 76241]
 [77090 60611 74223 60225 21509 72106]]


TODO: Extract suspects [1,3] months [2,4]

In [964]:
special_tx = transactions[np.ix_([1,3],[2,4])]

---

In [965]:
print("\n Scene 7: Fingerprint Evidence")
("3 fingerprint scans as 4x4 images.")
fingerprints = np.random.randint(0, 255, size=(3, 4, 4))
fingerprints


 Scene 7: Fingerprint Evidence


array([[[230, 239, 183, 206],
        [ 31,  99,  73, 179],
        [177, 235,  26, 130],
        [212, 176, 254, 131]],

       [[ 52, 183, 248, 136],
        [239,  77,  44, 223],
        [231, 168, 163, 213],
        [ 13, 122,  65, 195]],

       [[231, 243, 157,  49],
        [146, 208, 206, 184],
        [173, 119,  43, 156],
        [144, 201,  62, 105]]])

TODO: Extract center 2x2 region of each image

In [966]:
centers = fingerprints[np.ix_(np.arange(fingerprints.shape[0]),[1,2],[1,2])]
centers

array([[[ 99,  73],
        [235,  26]],

       [[ 77,  44],
        [168, 163]],

       [[208, 206],
        [119,  43]]])

In [967]:
centers = fingerprints[np.ix_(np.arange(fingerprints.shape[0]),[1,2],[1,2])]
fingerprints[fingerprints<100] = 0
cleaned_fingerprints = fingerprints
cleaned_fingerprints

array([[[230, 239, 183, 206],
        [  0,   0,   0, 179],
        [177, 235,   0, 130],
        [212, 176, 254, 131]],

       [[  0, 183, 248, 136],
        [239,   0,   0, 223],
        [231, 168, 163, 213],
        [  0, 122,   0, 195]],

       [[231, 243, 157,   0],
        [146, 208, 206, 184],
        [173, 119,   0, 156],
        [144, 201,   0, 105]]])

---


In [968]:
print("\n Scene 8: Decoding the Cipher")
print("A coded message: [65, 66, 67, 68, 69]")
cipher = np.array([65, 66, 67, 68, 69])



 Scene 8: Decoding the Cipher
A coded message: [65, 66, 67, 68, 69]


TODO: Convert to characters


In [969]:
message = np.vectorize(chr)(cipher)
print("\nScene 8 Result → Secret message:",message)


Scene 8 Result → Secret message: ['A' 'B' 'C' 'D' 'E']


---


In [970]:
print("\n Scene 9: Narrowing the Suspects")
print("Remaining 4 suspects: Height, Weight, Age")
suspects_data = np.random.randint(20, 100, size=(4, 3))
suspects_data


 Scene 9: Narrowing the Suspects
Remaining 4 suspects: Height, Weight, Age


array([[81, 39, 87],
       [45, 66, 43],
       [72, 36, 47],
       [61, 71, 58]])

TODO: Extract suspects with weight > 70 and age < 30


In [971]:
filtered_suspects = suspects_data[(suspects_data[:,1]>70)&(suspects_data[:,2]<30)]
print("\nScene 9 Result → Filtered suspects:\n", filtered_suspects)


Scene 9 Result → Filtered suspects:
 []


---

In [972]:
print("\n️ Scene 10: The Final Chase")
print("2 cars tracked every 3 hours for 2 days → shape (2,2,8)")
cars_tracking = np.random.randint(0, 50, size=(2, 2, 8))



️ Scene 10: The Final Chase
2 cars tracked every 3 hours for 2 days → shape (2,2,8)


TODO: Transpose to (2,8,2)


In [973]:
cars_transposed = cars_tracking.transpose(0,2,1)
cars_tracking.shape


(2, 2, 8)

In [974]:
same_location_times = []
for i in range(temp.shape[1]):
  if np.array_equal(temp[0,i],temp[1,i]):
    same_location_times.append(temp[0,i][1])

print("\nScene 10 Result → Same location times:", same_location_times)


Scene 10 Result → Same location times: [np.int64(4), np.int64(4)]


---


In [975]:
print("\n️ Final Verdict")
print("Combine results to reveal the PRIME SUSPECT!")


️ Final Verdict
Combine results to reveal the PRIME SUSPECT!


TODO: Combine logic → pick suspect ID based on patterns

In [976]:
print("\n The Prime Suspect is:", "???")


 The Prime Suspect is: ???


In [977]:
# high_activity_count
# even_index_ages
# youngest
# oldest
# avg_entry
# quick_visits
# max_day
# subset_traffic
# gps_transposed
# suspect2_movements
# big_spenders
# special_tx
# centers
# fingerprints_clean
# message
# filtered_suspects
# cars_transposed
# same_location_times
# prime_suspect