1. Sales Data Analysis

In [122]:
import numpy as np
# OrderID	CustomerID	CustomerName	Segment	Region	OrderDate	ProductCategory	SalesAmount	Quantity	Discount	Profit salesRep
sales_data_np = np.array([
    [1001, 'C001', 'Alice Johnson', 'Consumer', 'East', '2025-08-01', 'Furniture', 1200.50, 2, 0.10, 300.12, 'William Clark'],
    [1002, 'C002', 'Bob Smith', 'Corporate', 'West', '2025-08-03', 'Office Supplies', 450.75, 5, 0.05, 90.15, 'Olivia Martinez'],
    [1003, 'C003', 'Carol Lee', 'Home Office', 'Central', '2025-08-05', 'Technology', 890.00, 1, 0.20, 150.50, 'James Wilson'],
    [1004, 'C004', 'David Kim', 'Consumer', 'South', '2025-08-07', 'Furniture', 670.80, 3, 0.15, 120.30, 'Olivia Martinez'],
    [1005, 'C005', 'Emma Davis', 'Corporate', 'East', '2025-08-09', 'Office Supplies', 310.25, 4, 0.00, 70.40, 'William Clark'],
    [1006, 'C006', 'Frank Wilson', 'Consumer', 'Central', '2025-08-11', 'Technology', 1500.00, 2, 0.25, 250.00, 'James Wilson'],
    [1007, 'C007', 'Grace Chen', 'Home Office', 'West', '2025-08-13', 'Furniture', 920.45, 1, 0.05, 200.10, 'Olivia Martinez'],
    [1008, 'C008', 'Henry Patel', 'Consumer', 'East', '2025-08-15', 'Office Supplies', 540.60, 6, 0.10, 130.50, 'William Clark'],
    [1009, 'C009', 'Irene Lopez', 'Corporate', 'South', '2025-08-17', 'Technology', 720.00, 3, 0.15, 180.00, 'William Clark'],
    [1010, 'C010', 'Jack Brown', 'Consumer', 'Central', '2025-08-19', 'Furniture', 1100.80, 4, 0.20, 250.00, 'Olivia Martinez']
])
sales_data_np

array([['1001', 'C001', 'Alice Johnson', 'Consumer', 'East',
        '2025-08-01', 'Furniture', '1200.5', '2', '0.1', '300.12',
        'William Clark'],
       ['1002', 'C002', 'Bob Smith', 'Corporate', 'West', '2025-08-03',
        'Office Supplies', '450.75', '5', '0.05', '90.15',
        'Olivia Martinez'],
       ['1003', 'C003', 'Carol Lee', 'Home Office', 'Central',
        '2025-08-05', 'Technology', '890.0', '1', '0.2', '150.5',
        'James Wilson'],
       ['1004', 'C004', 'David Kim', 'Consumer', 'South', '2025-08-07',
        'Furniture', '670.8', '3', '0.15', '120.3', 'Olivia Martinez'],
       ['1005', 'C005', 'Emma Davis', 'Corporate', 'East', '2025-08-09',
        'Office Supplies', '310.25', '4', '0.0', '70.4', 'William Clark'],
       ['1006', 'C006', 'Frank Wilson', 'Consumer', 'Central',
        '2025-08-11', 'Technology', '1500.0', '2', '0.25', '250.0',
        'James Wilson'],
       ['1007', 'C007', 'Grace Chen', 'Home Office', 'West',
        '2025-08-13', 'F

In [123]:
cat = np.unique(sales_data_np[:,3])
for i in cat:
    data = sales_data_np[sales_data_np[:,3]==i]
    sales = data[:-2]
    print(i,' ',len(data))

Consumer   5
Corporate   3
Home Office   2


In [124]:
rep = np.unique(sales_data_np[:,-1])
for i in rep:
    data = sales_data_np[sales_data_np[:,-1]==i]
    sales = np.sum(data[:,-2].astype(float))
    print(i,' ',sales)

James Wilson   400.5
Olivia Martinez   660.55
William Clark   681.02


In [125]:
reg = np.unique(sales_data_np[:,4])
# reg
for i in reg:
    data = sales_data_np[sales_data_np[:,4]==i]
    avg = np.mean(data[:,-5].astype(float))
    print(i,' ',avg)

Central   1163.6000000000001
East   683.7833333333333
South   695.4
West   685.6


2. Employee Data Analysis

In [126]:
import numpy as np
# EmployeeID	Name	Department	Salary	PerformanceScore
employee_data = np.array([
    ['E001', 'Alice Brown', 'HR', 55000, 8.5],
    ['E002', 'Bob Smith', 'IT', 72000, 7.2],
    ['E003', 'Carol Lee', 'Finance', 68000, 9.0],
    ['E004', 'David Kim', 'IT', 75000, 6.5],
    ['E005', 'Emma Davis', 'Marketing', 50000, 8.0],
    ['E006', 'Frank Wilson', 'HR', 53000, 7.8],
    ['E007', 'Grace Chen', 'Finance', 67000, 8.9],
    ['E008', 'Henry Patel', 'Marketing', 52000, 7.5],
    ['E009', 'Irene Lopez', 'IT', 71000, 9.3],
    ['E010', 'Jack Brown', 'HR', 56000, 6.8]
])

In [127]:
dep = np.unique(employee_data[:,2])
for i in dep:
    data = employee_data[employee_data[:,2]==i]
    print(i,' ',len(data))

Finance   2
HR   3
IT   3
Marketing   2


In [128]:
employee_data[np.argsort(employee_data[:,-2].astype(float))][len(employee_data)-1]

array(['E004', 'David Kim', 'IT', '75000', '6.5'], dtype='<U32')

In [129]:
dep = np.unique(employee_data[:,2])
for i in dep:
    data = employee_data[employee_data[:,2]==i]
    avg = np.mean(data[:,-2].astype(float))
    print(i,' ',avg)

Finance   67500.0
HR   54666.666666666664
IT   72666.66666666667
Marketing   51000.0


In [130]:
employee_data[np.argsort(employee_data[:,-1])]

array([['E004', 'David Kim', 'IT', '75000', '6.5'],
       ['E010', 'Jack Brown', 'HR', '56000', '6.8'],
       ['E002', 'Bob Smith', 'IT', '72000', '7.2'],
       ['E008', 'Henry Patel', 'Marketing', '52000', '7.5'],
       ['E006', 'Frank Wilson', 'HR', '53000', '7.8'],
       ['E005', 'Emma Davis', 'Marketing', '50000', '8.0'],
       ['E001', 'Alice Brown', 'HR', '55000', '8.5'],
       ['E007', 'Grace Chen', 'Finance', '67000', '8.9'],
       ['E003', 'Carol Lee', 'Finance', '68000', '9.0'],
       ['E009', 'Irene Lopez', 'IT', '71000', '9.3']], dtype='<U32')

3. Student Grades Analysis

In [131]:
import numpy as np
#StudentID	Name	Math	Science	English	History
student_data = np.array([
    ['S001', 'Alice Brown', 85, 78, 92, 74],
    ['S002', 'Bob Smith', 58, 64, 10, 66],
    ['S003', 'Carol Lee', 95, 18, 82, 91],
    ['S004', 'David Kim', 76, 85, 20, 79],
    ['S005', 'Emma Davis', 66, 72, 68, 70],
    ['S006', 'Frank Wilson', 90, 95, 88, 92],
    ['S007', 'Grace Chen', 72, 10, 75, 65],
    ['S008', 'Henry Patel', 81, 79, 85, 80],
    ['S009', 'Irene Lopez', 69, 14, 17, 71],
    ['S010', 'Jack Brown', 88, 10, 86, 19]
])


In [132]:
count=0
for i in student_data:
    marks = i[2:].astype(int)
    total = np.sum(marks>20)
    if total==4:
        count+=1
print(count)

4


In [133]:
sub=['Math'	,'Science',	'English'	,"History"]
avg = np.mean(student_data[:,2:].astype(int),axis=0)
j=0
for i in sub:
    print(i," ",avg[j])
    j+=1

Math   78.0
Science   52.5
English   62.3
History   70.7


In [134]:
student_data[np.argmax(np.sum(student_data[:,2:].astype(int),axis=1))]

array(['S006', 'Frank Wilson', '90', '95', '88', '92'], dtype='<U21')

In [135]:
student_data[np.argsort(np.mean(student_data[:,2:].astype(int),axis=1))][::-1][0:3]

array([['S006', 'Frank Wilson', '90', '95', '88', '92'],
       ['S001', 'Alice Brown', '85', '78', '92', '74'],
       ['S008', 'Henry Patel', '81', '79', '85', '80']], dtype='<U21')

4. Weather Data Analysis

In [136]:
import numpy as np

# WeatherID   Month    Temp(°C)  Rainfall(mm)
weather_data = np.array([
    ['Winter',   'January',   22,  10],
    ['Winter',   'January',   24,   5],
    ['Winter',   'January',   20,   8],

    ['Winter',   'February',  25,   7],
    ['Winter',   'February',  27,  12],
    ['Winter',   'February',  23,   9],

    ['Spring',   'March',     30,   4],
    ['Spring',   'March',     32,   6],
    ['Spring',   'March',     28,   5],

    ['Summer',   'April',     34,   2],
    ['Summer',   'April',     36,   3],
    ['Summer',   'April',     35,   1],

    ['Summer',   'May',       37,   0],
    ['Summer',   'May',       38,   2],
    ['Summer',   'May',       39,   1],

    ['Monsoon',  'June',      40,  30],
    ['Monsoon',  'June',      39,  25],
    ['Monsoon',  'June',      41,  28],

    ['Monsoon',  'July',      36,  45],
    ['Monsoon',  'July',      37,  42],
    ['Monsoon',  'July',      35,  50],

    ['Monsoon',  'August',    33,  40],
    ['Monsoon',  'August',    34,  38],
    ['Monsoon',  'August',    35,  35],

    ['Autumn',   'September', 32,  25],
    ['Autumn',   'September', 31,  28],
    ['Autumn',   'September', 33,  22],

    ['Autumn',   'October',   28,  15],
    ['Autumn',   'October',   27,  18],
    ['Autumn',   'October',   29,  12],

    ['Winter',   'November',  24,  20],
    ['Winter',   'November',  26,  22],
    ['Winter',   'November',  23,  18],

    ['Winter',   'December',  21,  30],
    ['Winter',   'December',  22,  25],
    ['Winter',   'December',  20,  28]
])


In [137]:
month = np.unique(weather_data[:,1])
for i in month:
    monthdata = weather_data[weather_data[:,1]==i]
    max = monthdata[np.argmax(monthdata[:,2].astype(float))][2]
    min = monthdata[np.argmin(monthdata[:,2].astype(float))][2]
    print(i," ",min," ",max)

April   34   36
August   33   35
December   20   22
February   23   27
January   20   24
July   35   37
June   39   41
March   28   32
May   37   39
November   23   26
October   27   29
September   31   33


In [138]:
sea = np.unique(weather_data[:,0])
for i in sea:
    seadata = weather_data[weather_data[:,0]==i]
    mean_rain = np.mean(seadata[:,-1].astype(float))
    print(i," ",mean_rain)

Autumn   20.0
Monsoon   37.0
Spring   5.0
Summer   1.5
Winter   16.166666666666668


In [139]:
month = np.unique(weather_data[:,1])
days = 0
for i in month:
    monthdata = weather_data[weather_data[:,1]==i]
    monttemp = sum(monthdata[:,-2].astype(float)>35)
    days+=monttemp*10
print(days)

90


In [146]:
month = np.unique(weather_data[:,1])
temp = []
for i in month:
    monthdata = weather_data[weather_data[:,1]==i]
    monttemp = np.mean(monthdata[:,-2].astype(float))
    temp.append(monttemp)
print(month[np.argmax(temp)]," ",temp[np.argmax(temp)])

June   40.0


5. Stock Market Data Analysis

In [148]:
import numpy as np

# StockID   Date        Company        Price
stock_data = np.array([
    ['ST001', '2025-01-01', 'AlphaTech',   150],
    ['ST002', '2025-01-01', 'BetaCorp',    220],
    ['ST003', '2025-01-01', 'GammaLtd',    310],

    ['ST004', '2025-01-02', 'AlphaTech',   155],
    ['ST005', '2025-01-02', 'BetaCorp',    215],
    ['ST006', '2025-01-02', 'GammaLtd',    320],

    ['ST007', '2025-01-03', 'AlphaTech',   160],
    ['ST008', '2025-01-03', 'BetaCorp',    225],
    ['ST009', '2025-01-03', 'GammaLtd',    315],

    ['ST010', '2025-01-04', 'AlphaTech',   158],
    ['ST011', '2025-01-04', 'BetaCorp',    230],
    ['ST012', '2025-01-04', 'GammaLtd',    318],

    ['ST013', '2025-01-05', 'AlphaTech',   162],
    ['ST014', '2025-01-05', 'BetaCorp',    228],
    ['ST015', '2025-01-05', 'GammaLtd',    325],

    ['ST016', '2025-01-06', 'AlphaTech',   165],
    ['ST017', '2025-01-06', 'BetaCorp',    235],
    ['ST018', '2025-01-06', 'GammaLtd',    330]
])


In [ ]:
stock = np.unique(stock_data[:,-2])
for i in stock:
    stock_ = stock_data[stock_data[:,-2]==i]
    price = stock_[:,-1].astype(int)
    print(i)
    for j in range(1,len(price)-1):
        print(f"day{j+1} : ",(price[j]-price[j-1])/price[j-1])


AlphaTech
day2 :  0.03333333333333333
day3 :  0.03225806451612903
day4 :  -0.0125
day5 :  0.02531645569620253
BetaCorp
day2 :  -0.022727272727272728
day3 :  0.046511627906976744
day4 :  0.022222222222222223
day5 :  -0.008695652173913044
GammaLtd
day2 :  0.03225806451612903
day3 :  -0.015625
day4 :  0.009523809523809525
day5 :  0.0220125786163522


In [ ]:
stock = np.unique(stock_data[:,-2])
avg=[]
for i in stock:
    stock_ = stock_data[stock_data[:,-2]==i]
    price = stock_[:,-1].astype(int)
    temp_stor=[]
    for j in range(1,len(price)-1):
        temp_stor.append((price[j]-price[j-1])/price[j-1])
    avg.append(np.mean(temp_stor))
    
stock[np.argmax(avg)]

np.str_('AlphaTech')

In [207]:
stock = np.unique(stock_data[:,-2])
days = []
for i in stock:
    count=0
    stock_ = stock_data[stock_data[:,-2]==i]
    price = stock_[:,-1].astype(int)
    for j in range(1,len(price)-1):
        if(price[j]-price[j-1])/price[j-1]>=0:
            count+=1
    days.append(count)

for i,j in zip(stock,days):
    print(i,j)


AlphaTech 3
BetaCorp 2
GammaLtd 3


In [219]:
stock = np.unique(stock_data[:,-2])
max_drop=[]
for i in stock:
    stock_ = stock_data[stock_data[:,-2]==i]
    price = stock_[:,-1].astype(int)
    temp_stor=[]
    for j in range(1,len(price)-1):
        temp_stor.append((price[j]-price[j-1])/price[j-1])
    max = temp_stor[np.argmax(temp_stor)]
    min = temp_stor[np.argmin(temp_stor)]
    max_drop.append(max-min)
    
print(stock[np.argmax(max_drop)]," ",max_drop[np.argmax(max_drop)])

BetaCorp   0.06923890063424948


6. Hospital Patient Data Analysis

In [220]:
import numpy as np

#patient_id age department disease_category days_stayed
patient_data = np.array([
    ('P001', 45, 'Cardiology', 'Heart Disease', 7),
    ('P002', 30, 'Neurology', 'Stroke', 10),
    ('P003', 65, 'Orthopedics', 'Fracture', 5),
    ('P004', 50, 'Cardiology', 'Heart Disease', 12),
    ('P005', 40, 'Neurology', 'Migraine', 3),
    ('P006', 70, 'Cardiology', 'Arrhythmia', 8),
    ('P007', 60, 'Orthopedics', 'Arthritis', 15),
    ('P008', 55, 'Neurology', 'Stroke', 6),
    ('P009', 35, 'Cardiology', 'Heart Disease', 9),
    ('P010', 28, 'Orthopedics', 'Fracture', 4)
])


Count the number of patients per disease category.•

In [238]:
cat = np.unique(patient_data[:,-2])
for i in cat:
    pdata = patient_data[patient_data[:,-2]==i]
    print(i," ",len(pdata))

Arrhythmia   1
Arthritis   1
Fracture   2
Heart Disease   3
Migraine   1
Stroke   2


Find the patient with the longest hospital stay.•

In [231]:
patient_data[np.argmax(patient_data[:,-1].astype(int))]

array(['P007', '60', 'Orthopedics', 'Arthritis', '15'], dtype='<U21')

Calculate average age of patients per department.•

In [235]:
dep = np.unique(patient_data[:,-2])
avg = []
for i in dep:
    tempdata = patient_data[patient_data[:,-2]==i]
    tempavg = np.mean(tempdata[:,1].astype(float))
    avg.append(tempavg)
for i,j in zip(dep,avg):
    print(i," ",j)

Arrhythmia   70.0
Arthritis   60.0
Fracture   46.5
Heart Disease   43.333333333333336
Migraine   40.0
Stroke   42.5


Identify the most common diagnosis.•

In [237]:
cat = np.unique(patient_data[:,-2])
count=[]
for i in cat:
    pdata = patient_data[patient_data[:,-2]==i]
    count.append(len(pdata))
cat[np.argmax(count)]

np.str_('Heart Disease')

7. E-commerce Website Traffic Analysis

In [242]:
import numpy as np

# 'visitor_id','date','pages_visited','time_spent',

ecom = np.array([
    ['V001', '2025-09-01', 5, 12.5],
    ['V002', '2025-09-01', 1, 3.0],
    ['V003', '2025-09-02', 3, 7.2],
    ['V001', '2025-09-02', 2, 6.5],
    ['V002', '2025-09-03', 1, 2.0],
    ['V003', '2025-09-03', 4, 15.0],
    ['V004', '2025-09-04', 3, 20.0],
    ['V002', '2025-09-05', 1, 1.5],
    ['V003', '2025-09-06', 2, 5.0],
    ['V001', '2025-09-07', 3, 10.]
])


Count the number of visitors per day/week.•

In [247]:
day = np.unique(ecom[:,1])
visit = []
for i in day:
    tempdata = ecom[ecom[:,1]==i]
    tempvis = np.sum(tempdata[:,-2].astype(float))
    visit.append(tempvis)
for i,j in zip(day,visit):
    print(i," ",j)

2025-09-01   6.0
2025-09-02   5.0
2025-09-03   5.0
2025-09-04   3.0
2025-09-05   1.0
2025-09-06   2.0
2025-09-07   3.0


Find the day with the highest number of visitors.•

In [249]:
print(day[np.argmax(visit)]," ",visit[np.argmax(visit)])

2025-09-01   6.0


Calculate average time spent by users on the website.•

In [250]:
user = np.unique(ecom[:,0])
time = []
for i in user:
    tempdata = ecom[ecom[:,0]==i]
    temptime = np.sum(tempdata[:,-1].astype(float))
    time.append(temptime)
for i,j in zip(user,time):
    print(i," ",j)

V001   29.0
V002   6.5
V003   27.2
V004   20.0


Determine bounce rate (users who visited only 1 page).•

-----

In [262]:
data = np.array([np.random.randint(1000,10000) for i in range(0,20)])
# dna_data = np.array([np.random.randint(0,4) for i in range(0,20)])
data

array([9192, 7309, 4055, 3449, 1967, 1277, 4440, 6952, 8770, 6677, 2089,
       9897, 2881, 6302, 9108, 1957, 3563, 2223, 9715, 2347])

In [270]:
data = np.random.randint(0,63,size=(8,8))
data[np.ix_([0,2,4,6],[1,3,5,7])]=-1
data[np.ix_([1,3,5,7],[0,2,4,6])]=-1
data

array([[33, -1, 11, -1, 16, -1, 14, -1],
       [-1, 59, -1, 26, -1, 31, -1, 27],
       [58, -1, 57, -1, 48, -1,  2, -1],
       [-1, 17, -1, 59, -1, 16, -1, 19],
       [58, -1, 23, -1, 30, -1, 27, -1],
       [-1,  1, -1,  6, -1,  1, -1, 26],
       [31, -1, 35, -1, 30, -1, 39, -1],
       [-1, 62, -1, 25, -1,  5, -1, 26]], dtype=int32)

In [272]:
data = np.random.randint(0,10,size=(4,3,3))
data[:,1,1]

array([0, 9, 1, 9], dtype=int32)

Problem 14: Sports Team Analytics
Create a (5, 6, 4) array → 5 teams, 6 matches, 4 stats each.
Extract stats of teams [1, 3, 4] for matches [2, 5].•
Problem 15: Movie Ratings


In [ ]:
data = np.random.randint(0,10,size=(5,6,4))
data[np.ix_([1,3,4],[2,5])]

Problem 16: IoT Device Monitoring

Create a (3, 24, 7) array → 3 devices, 24 hours, 7 days.
Extract hourly readings for devices [0, 2] on days [1, 3, 5]

In [282]:
np.arange(data.shape[1])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [289]:
data = np.random.randint(0,100,size=(3,24,7))
data[np.ix_([0,2],np.arange(data.shape[1]),[1,3,5])]
# data[np.ix_([0,2],range(24),[1,3,5])]

array([[[46, 56, 67],
        [84, 32, 79],
        [30, 21, 21],
        [30, 32, 22],
        [ 8, 84, 35],
        [15, 96, 77],
        [86, 27,  7],
        [75, 55, 59],
        [85, 45, 82],
        [21, 99, 90],
        [29, 20, 19],
        [44, 62, 90],
        [83, 62, 15],
        [10, 98, 16],
        [ 3, 10, 83],
        [81, 28, 67],
        [18, 83, 88],
        [ 9, 26, 64],
        [41, 56, 20],
        [24, 74, 70],
        [97, 59,  3],
        [23, 30, 98],
        [78, 26,  0],
        [25, 33, 31]],

       [[30, 22, 50],
        [53, 98, 65],
        [82, 81, 80],
        [87, 21, 68],
        [36, 70, 41],
        [43, 77, 75],
        [61, 60, 81],
        [52, 62, 91],
        [65,  7, 69],
        [42, 49, 93],
        [32, 35, 28],
        [ 6, 35, 70],
        [39, 53, 99],
        [68, 30, 60],
        [91, 67, 74],
        [73, 21, 71],
        [ 3, 44,  6],
        [52, 16, 34],
        [96,  0, 17],
        [72, 81, 16],
        [63, 19,  0],
        

In [292]:
data = np.random.randint(0,100,size=(4,10,6))
data[np.ix_([1,3],[2,5,7],[0,2,4])]

array([[[30, 17, 34],
        [27, 91, 57],
        [ 8, 95, 64]],

       [[28, 17,  3],
        [12, 35, 52],
        [71, 38, 42]]], dtype=int32)

In [295]:
data = np.random.randint(0,100,size=(5,28,28))
data[np.ix_(np.arange(data.shape[0]),[0,data.shape[1]-1],[0,data.shape[2]-1])]

array([[[ 1, 70],
        [82, 73]],

       [[40, 66],
        [40, 71]],

       [[46, 39],
        [49,  0]],

       [[72, 63],
        [31,  2]],

       [[91, 10],
        [21, 39]]], dtype=int32)